<?php
$table_name = "{$wpdb->prefix}pw_countries";

// insert contry data
$sql = <<<EOD
			INSERT INTO `{$table_name}` (`country_code`,`country_name`) VALUES 
				('ABW','Aruba'),
				('AFG','Afghanistan'),
				('AGO','Angola'),
				('AIA','Anguilla'),
				('ALB','Albania'),
				('AND','Andorra'),
				('ANT','Netherlands Antilles'),
				('ARE','United Arab Emirates'),
				('ARG','Argentina'),
				('ARM','Armenia'),
				('ASM','American Samoa'),
				('ATA','Antarctica'),
				('ATF','French Southern Terr.'),
				('ATG','Antigua Barbuda'),
				('AUS','Australia'),
				('AUT','Austria'),
				('AZE','Azerbaijan'),
				('BDI','Burundi'),
				('BEL','Belgium'),
				('BEN','Benin'),
				('BFA','Burkina Faso'),
				('BGD','Bangladesh'),
				('BGR','Bulgaria'),
				('BHS','Bahamas'),
				('BIH','Bosnia Herzegowina'),
				('BLR','Belarus'),
				('BLZ','Belize'),
				('BMU','Bermuda'),
				('BOL','Bolivia'),
				('BRA','Brazil'),
				('BRB','Barbados'),
				('BRN','Brunei Darussalam'),
				('BTN','Bhutan'),
				('BVT','Bouvet Island'),
				('BWA','Botswana'),
				('CAF','Central African Rep'),
				('CAN','Canada'),
				('CCK','Cocos (Keeling) Isles'),
				('CHE','Switzerland'),
				('CHL','Chile'),
				('CHN','China'),
				('CIV','Cote D Ivoire'),
				('CMR','Cameroon'),
				('COG','Congo'),
				('COK','Cook Islands'),
				('COL','Colombia'),
				('COM','Comoros'),
				('CPV','Cape Verde'),
				('CRI','Costa Rica'),
				('CUB','Cuba'),
				('CXR','Christmas Island'),
				('CYM','Cayman Islands'),
				('CYP','Cyprus'),
				('CZE','Czech Republic'),
				('DEU','Germany'),
				('DJI','Djibouti'),
				('DMA','Dominica'),
				('DOM','Dominican Republic'),
				('DNK','Denmark'),
				('DZA','Algeria'),
				('ECU','Ecuador'),
				('EGY','Egypt'),
				('ENG','England'),
				('ERI','Eritrea'),
				('ESH','Western Sahara'),
				('ESP','Spain'),
				('EST','Estonia'),
				('ETH','Estonia'),
				('EU', 'European Union'),
				('FIN','Finland'),
				('FJI','Fiji'),
				('FLK','Falkland Islands (Malvinas)'),
				('FRA','France'),
				('FRO','Faroe Islands'),
				('FSM','Micronesia, Fed States'),
				('FXX','France, Metro'),
				('GAB','Gabon'),
				('GBR','United Kingdom'),
				('GEO','Georgia'),
				('GHA','Ghana'),
				('GIB','Gibraltar'),
				('GIN','Guinea'),
				('GLP','Guadeloupe'),
				('GMB','Gambia'),
				('GNB','Guinea-Bissau'),
				('GNQ','Equatorial Guinea'),
				('GRC','Greece'),
				('GRD','Grenada'),
				('GRL','Greenland'),
				('GTM','Guatemala'),
				('GUF','French Guiana'),
				('GUM','Guam'),
				('GUY','Guyana'),
				('HKG','Hong Kong'),
				('HMD','Heard And Mc Donald Isles'),
				('HND','Honduras'),
				('HRV','Croatia (Hrvatska)'),
				('HTI','Haiti'),
				('HUN','Hungary'),
				('IDN','Indonesia'),
				('IND','India'),
				('IOT','British Indian Ocean Terr.'),
				('IRL','Ireland'),
				('IRN','Iran (Islamic Rep)'),
				('IRQ','Iraq'),
				('ISL','Iceland'),
				('ISR','Israel'),
				('ITA','Italy'),
				('JAM','Jamaica'),
				('JOR','Jordan'),
				('JPN','Japan'),
				('KAZ','Kazakhstan'),
				('KEN','Kenya'),
				('KGZ','Kyrgyzstan'),
				('KHM','Cambodia'),
				('KIR','Kiribati'),
				('KNA','Saint Kitts Nevis'),
				('KOR','Korea, Republic Of'),
				('KWT','Kuwait'),
				('LAO','LAO'),
				('LBN','Lebanon'),
				('LBR','Liberia'),
				('LBY','Libyan Arab Jamahiriya'),
				('LCA','Saint Lucia'),
				('LIE','Liechtenstein'),
				('LKA','Sri Lanka'),
				('LSO','Lesotho'),
				('LTU','Lithuania'),
				('LUX','Luxembourg'),
				('LVA','Latvia'),
				('MAC','Macau'),
				('MAR','Morocco'),
				('MCO','Monaco'),
				('MDA','Moldova, Rep'),
				('MDG','Madagascar'),
				('MDV','Maldives'),
				('MEX','Mexico'),
				('MHL','Marshall Islands'),
				('MKD','Macedonia, former Yugoslav'),
				('MLI','Mali'),
				('MLT','Malta'),
				('MMR','Myanmar'),
				('MNG','Mongolia'),
				('MNP','Northern Mariana Isles'),
				('MOZ','Mozambique'),
				('MRT','Mauritania'),
				('MSR','Montserrat'),
				('MTQ','Martinique'),
				('MUS','Mauritius'),
				('MWI','Malawi'),
				('MYS','Malaysia'),
				('MYT','Mayotte'),
				('NAM','Namibia'),
				('NCL','New Caledonia'),
				('NER','Niger'),
				('NFK','Norfolk Island'),
				('NGA','Nigeria'),
				('NIC','Nicaragua'),
				('NIU','Niue'),
				('NLD','Netherlands'),
				('NOR','Norway'),
				('NPL','Nepal'),
				('NRU','Nauru'),
				('NZL','New Zealand'),
				('OMN','Oman'),
				('PAK','Pakistan'),
				('PAN','Panama'),
				('PCN','Pitcairn'),
				('PER','Peru'),
				('PHL','Philippines'),
				('PLW','Palau'),
				('PNG','Papua New Guinea'),
				('POL','Poland'),
				('PRI','Puerto Rico'),
				('PRK','Korea, Dem People s Rep'),
				('PRT','Portugal'),
				('PRY','Paraguay'),
				('PYF','French Polynesia'),
				('QAT','Qatar'),
				('REU','Reunion'),
				('ROM','Romania'),
				('RUS','Russian Federation'),
				('RWA','Rwanda'),
				('SAU','Saudi Arabia'),
				('SCO','Scotland'),
				('SDN','Sudan'),
				('SEN','Senegal'),
				('SGP','Singapore'),
				('SGS','S Georgia Sandwich Isles'),
				('SHN','St. Helena'),
				('SJM','Svalbard &amp; Jan Mayen Islands'),
				('SLB','Solomon Islands'),
				('SLE','Sierra Leona'),
				('SLV','El Salvador'),
				('SMR','San Marino'),
				('SOM','Somalia'),
				('SPM','St. Pierre &amp; Miquelon'),
				('STP','Sao Tome Principe'),
				('SUR','Suriname'),
				('SVK','Slovakia (Slovak Rep)'),
				('SVN','Slovenia'),
				('SWE','Sweden'),
				('SWZ','Swaziland'),
				('SYC','Seychelles'),
				('SYR','Syrian Arab Republic'),
				('TCA','Turks Caicos Islands'),
				('TCD','Chad'),
				('TGO','Togo'),
				('THA','Thailand'),
				('TJK','Tajikistan'),
				('TKL','Tokelau'),
				('TKM','Turkmenistan'),
				('TMP','East Timor'),
				('TON','Tonga'),
				('TTO','Trinidad Tobago'),
				('TUN','Tunisia'),
				('TUR','Turkey'),
				('TUV','Tuvalu'),
				('TWN','Taiwan, Province Of China'),
				('TZA','Tanzania, United Rep'),
				('UGA','Uganda'),
				('UKR','Ukraine'),
				('UMI','US Minor Outlying Isles'),
				('URY','Uruguay'),
				('USA','United States'),
				('UZB','Uzbekistan'),
				('VAT','Holy See (Vatican)'),
				('VCT','Saint Vincent Grenadines'),
				('VEN','Venezuela'),
				('VGB','Virgin Isles (British)'),
				('VIR','Virgin Isles (U.S.)'),
				('VNM','Viet Nam'),
				('VUT','Vanuatu'),
				('WLF','Wallis Futuna Islands'),
				('WSM','Samoa'),
				('YEM','Yemen'),
				('YUG','Yugoslavia'),
				('ZAF','South Africa'),
				('ZMB','Zambia'),
				('ZWE','Zimbabwe');
EOD;
$wpdb->query($sql);

// insert country region data
$table_name = "{$wpdb->prefix}pw_country_region";
$sql = <<<EOD
			INSERT INTO `{$table_name}` (`country_code`,`region_code`,`region_name`) VALUES 
				('PHL','01','Abra'),
				('RUS','01','Respublika Adygeya'),
				('PHL','02','Agusan del Norte'),
				('RUS','02','Aginskiy Buryatskiy'),
				('PHL','03','Agusan del Sur'),
				('RUS','03','Respublika Altay'),
				('PHL','04','Aklan'),
				('RUS','04','Altayskiy Kray'),
				('PHL','05','Albay'),
				('RUS','05','Amurskaya'),
				('PHL','06','Antique'),
				('RUS','06','Arkhangel skaya'),
				('PHL','07','Bataan'),
				('RUS','07','Astrakhanskaya'),
				('PHL','08','Batanes'),
				('RUS','08','Respublika Bashkortostan'),
				('PHL','09','Batangas'),
				('RUS','09','Belgorodskaya'),
				('PHL','10','Benguet'),
				('RUS','10','Bryanskaya'),
				('PHL','11','Bohol'),
				('RUS','11','Respublika Buryatiya'),
				('PHL','12','Bukidnon'),
				('PHL','13','Bulacan'),
				('RUS','13','Chelyabinskaya'),
				('PHL','14','Cagayan'),
				('RUS','14','Chitinskaya'),
				('PHL','15','Camarines Norte'),
				('RUS','15','Chukotskiy'),
				('PHL','16','Camarines Sur'),
				('RUS','16','Chuvashskaya'),
				('PHL','17','Camiguin'),
				('RUS','17','Respublika Dagestan'),
				('PHL','18','Capiz'),
				('RUS','18','Evenkiyskiy'),
				('PHL','19','Catanduanes'),
				('PHL','20','Cavite'),
				('RUS','20','Irkutskaya'),
				('PHL','21','Cebu'),
				('RUS','21','Ivanovskaya'),
				('PHL','22','Basilan'),
				('RUS','22','Kabardino-Balkarskaya'),
				('PHL','23','Eastern Samar'),
				('RUS','23','Kaliningradskaya'),
				('PHL','24','Davao del Norte'),
				('RUS','24','Respublika Kalmykiya'),
				('PHL','25','Davao del Sur'),
				('RUS','25','Kaluzhskaya'),
				('PHL','26','Davao Oriental'),
				('RUS','26','Kamchatskaya'),
				('PHL','27','Ifugao'),
				('RUS','27','Karachayevo-Cherkesskaya'),
				('PHL','28','Ilocos Norte'),
				('RUS','28','Respublika Kareliya'),
				('PHL','29','Ilocos Sur'),
				('RUS','29','Kemerovskaya'),
				('PHL','30','Iloilo'),
				('RUS','30','Khabarovskiy Kray'),
				('PHL','31','Isabela'),
				('RUS','31','Respublika Khakasiya'),
				('PHL','32','Kalinga-Apayao'),
				('RUS','32','Khanty-Mansiyskiy'),
				('PHL','33','Laguna'),
				('RUS','33','Kirovskaya'),
				('PHL','34','Lanao del Norte'),
				('RUS','34','Respublika Komi'),
				('PHL','35','Lanao del Sur'),
				('RUS','35','Komi-Permyatskiy '),
				('PHL','36','La Union'),
				('RUS','36','Koryakskiy'),
				('PHL','37','Leyte'),
				('RUS','37','Kostromskaya'),
				('PHL','38','Marinduque'),
				('RUS','38','Krasnodarskiy Kray'),
				('PHL','39','Masbate'),
				('RUS','39','Krasnoyarskiy Kray'),
				('PHL','40','Mindoro Occidental'),
				('RUS','40','Kurganskaya'),
				('PHL','41','Mindoro Oriental'),
				('RUS','41','Kurskaya'),
				('PHL','42','Misamis Occidental'),
				('RUS','42','Leningradskaya'),
				('PHL','43','Misamis Oriental'),
				('RUS','43','Lipetskaya'),
				('PHL','44','Mountain Province'),
				('RUS','44','Magadanskaya'),
				('RUS','45','Respublika Mariy-El'),
				('PHL','46','Negros Oriental'),
				('RUS','46','Respublika Mordoviya'),
				('PHL','47','Nueva Ecija'),
				('RUS','47','Moskovskaya'),
				('PHL','48','Nueva Vizcaya'),
				('RUS','48','Gorod Moskva'),
				('PHL','49','Palawan'),
				('RUS','49','Murmanskaya'),
				('PHL','50','Pampanga'),
				('RUS','50','Nenetskiy'),
				('PHL','51','Pangasinan'),
				('RUS','51','Nizhegorodskaya'),
				('RUS','52','Novgorodskaya'),
				('PHL','53','Rizal'),
				('RUS','53','Novosibirskaya'),
				('PHL','54','Romblon'),
				('RUS','54','Omskaya'),
				('PHL','55','Samar'),
				('RUS','55','Orenburgskaya'),
				('PHL','56','Maguindanao'),
				('RUS','56','Orlovskaya'),
				('PHL','57','North Cotabato'),
				('RUS','57','Penzenskaya'),
				('PHL','58','Sorsogon'),
				('RUS','58','Permskaya'),
				('PHL','59','Southern Leyte'),
				('RUS','59','Primorskiy Kray'),
				('PHL','60','Sulu'),
				('RUS','60','Pskovskaya'),
				('PHL','61','Surigao del Norte'),
				('RUS','61','Rostovskaya'),
				('PHL','62','Surigao del Sur'),
				('RUS','62','Ryazanskaya'),
				('PHL','63','Tarlac'),
				('RUS','63','Respublika Sakha (Yakutiya)'),
				('PHL','64','Zambales'),
				('RUS','64','Sakhalinskaya'),
				('PHL','65','Zamboanga del Norte'),
				('RUS','65','Samarskaya'),
				('PHL','66','Zamboanga del Sur'),
				('RUS','66','Gorod Sankt-Peterburg'),
				('PHL','67','Northern Samar'),
				('RUS','67','Saratovskaya'),
				('PHL','68','Quirino'),
				('RUS','68','Respublika Severnaya Osetiya-Alaniya'),
				('PHL','69','Siquijor'),
				('RUS','69','Smolenskaya'),
				('PHL','70','South Cotabato'),
				('RUS','70','Stavropolskiy Kray'),
				('PHL','71','Sultan Kudarat'),
				('RUS','71','Sverdlovskaya'),
				('PHL','72','Tawi-Tawi'),
				('RUS','72','Tambovskaya'),
				('RUS','73','Respublika Tatarstan'),
				('RUS','74','Taymyrskiy (Dolgano-Nenetskiy)'),
				('RUS','75','Tomskaya'),
				('RUS','76','Tulskaya'),
				('RUS','77','Tverskaya '),
				('RUS','78','Tyumenskaya '),
				('RUS','79','Respublika Tyva'),
				('RUS','80','Udmurtskaya'),
				('RUS','81','Ulyanovskaya'),
				('RUS','82','Ust-Ordynskiy Buryatskiy'),
				('RUS','83','Vladimirskaya'),
				('RUS','84','Volgogradskaya'),
				('RUS','85','Vologodskaya'),
				('RUS','86','Voronezhskaya'),
				('RUS','87','Yamalo-Nenetskiy'),
				('RUS','88','Yaroslavskaya'),
				('RUS','89','Yevreyskaya'),
				('PHL','A1','Angeles City'),
				('PHL','A2','Bacolod City'),
				('PHL','A3','Bago City'),
				('PHL','A4','Baguio City'),
				('PHL','A7','Batangas City'),
				('PHL','A8','Butuan City'),
				('PHL','A9','Cabanatuan City'),
				('NOR','AAG','Aust-Agder'),
				('CAN','AB','Alberta'),
				('BHS','ABA','Abaco'),
				('ISL','ABA','Austur-Bardhastrandarsysla'),
				('ITA','ABR','Abruzzi'),
				('AZE','ABS','Abseron'),
				('IDN','ACE','Aceh'),
				('PRT','ACO','Acores'),
				('BRA','ACR','Acre'),
				('AUS','ACT','Australian Capital Territory'),
				('NGA','AD','Adamawa'),
				('TUR','ADA','Adana'),
				('AND','ADR','Andorra'),
				('DZA','ADR','Adrar'),
				('NER','AGA','Agadez'),
				('AZE','AGC','Agcabadi'),
				('AZE','AGD','Agdas'),
				('AZE','AGM','Agdam'),
				('AZE','AGS','Agstafa'),
				('MEX','AGS','Aguascalientes'),
				('AZE','AGU','Agsu'),
				('TKM','AHL','Ahal'),
				('KWT','AHM','Al-Ahmadi'),
				('ISL','AHU','Austur-Hunavatnssysla'),
				('SLV','AHU','Ahuachapan'),
				('JPN','AIC','Aichi'),
				('DZA','AID','Ain Defla'),
				('CHL','AIS','Aisen del General Carlos Ibanez del Campo'),
				('DZA','AIT','Ain Temouchent'),
				('GRC','AIY','Aegean Islands'),
				('USA','AK','Alaska'),
				('NOR','AKE','Akershus'),
				('JPN','AKI','Akita'),
				('USA','AL','Alabama'),
				('BRA','ALA','Alagoas'),
				('CRI','ALA','Alajuela'),
				('FIN','ALA','Alands Lan'),
				('ROM','ALB','Alba'),
				('PRT','ALE','Alentejo'),
				('DZA','ALG','Alger'),
				('PRT','ALG','Algarve'),
				('AZE','ALI','Ali Bayramli Sahari'),
				('FRA','ALS','Alsace'),
				('COL','ALT','Atlantico'),
				('PER','AMA','Amazonas'),
				('PRY','AMA','Amambay'),
				('VEN','AMA','Amazonas'),
				('BRA','AMP','Amapa'),
				('BRA','AMZ','Amazonas'),
				('IRQ','ANB','Anbar'),
				('PER','ANC','Ancash'),
				('BHS','AND','Andros'),
				('BRB','AND','Saint Andrew'),
				('ESP','AND','Andalucia'),
				('IND','AND','Andhra Pradesh'),
				('JAM','AND','Saint Andrews'),
				('UZB','AND','Andijon'),
				('AIA','ANG','Anguilla'),
				('VNM','ANG','An Giang'),
				('CHN','ANH','Anhui'),
				('IND','ANI','Andaman & Nicobar Islands'),
				('TUR','ANK','Ankara'),
				('DZA','ANN','Annaba'),
				('JAM','ANN','Saint Ann'),
				('ATG','ANT','Antigua & Barbuda'),
				('BEL','ANT','Antwerpen'),
				('CHL','ANT','Antofagasta'),
				('COL','ANT','Antioquia'),
				('MDG','ANT','Antananarivo'),
				('TUR','ANT','Antalya'),
				('VEN','ANZ','Anzoategui'),
				('JPN','AOM','Aomori'),
				('PRY','APG','Alto Paraguay'),
				('PRY','APR','Alto Parana'),
				('PER','APU','Apurimac'),
				('VEN','APU','Apure'),
				('FRA','AQU','Aquitaine'),
				('USA','AR','Arkansas'),
				('ARM','ARA','Aragatsotni'),
				('CHL','ARA','Araucania'),
				('ESP','ARA','Aragon'),
				('ROM','ARA','Arad'),
				('VEN','ARA','Aragua'),
				('IRQ','ARB','Arbil'),
				('ATA','ARC','Antarctica'),
				('PER','ARE','Arequipa'),
				('ROM','ARG','Arges'),
				('DNK','ARH','Arhus Amt'),
				('TUN','ARI','Ariana'),
				('ARM','ARM','Armaviri'),
				('ISL','ARN','Arnessysla'),
				('ARM','ARR','Ararati'),
				('URY','ART','Artigas'),
				('ABW','ARU','Aruba'),
				('IND','ARU','Arunachal Pradesh'),
				('USA','AS','American Samoa'),
				('MDG','ASI','Antsiranana'),
				('ISL','ASK','Austur-Skaftafellssysla'),
				('IND','ASS','Assam'),
				('AZE','AST','Astara'),
				('ESP','AST','Asturias'),
				('EGY','ASW','Al-Aswan'),
				('EGY','ASY','Asyut'),
				('CHL','ATA','Atacama'),
				('HND','ATL','Atlantida'),
				('NIC','ATN','Atlantico Norte'),
				('NIC','ATS','Atlantico Sur'),
				('GRC','ATT','Attiki'),
				('FRA','AUV','Auvergne'),
				('GTM','AVE','Alta Verapaz'),
				('PER','AYA','Ayacucho'),
				('TUR','AYD','Aydin'),
				('MMR','AYE','Ayeyarwady'),
				('USA','AZ','Arizona'),
				('DOM','AZU','Azua'),
				('ECU','AZU','Azuay'),
				('PHL','B1','Cadiz City'),
				('PHL','B2','Cagayan de Oro City'),
				('PHL','B3','Calbayog City'),
				('PHL','B4','Caloocan City'),
				('PHL','B5','Canlaon City'),
				('PHL','B6','Cavite City'),
				('PHL','B7','Cebu City'),
				('PHL','B8','Cotabato City'),
				('PHL','B9','Dagupan City'),
				('ARG','BA','Buenos Aires'),
				('NGA','BA','Bauchi'),
				('IRQ','BAB','Babil'),
				('HUN','BAC','Bacs-Kiskun Megye'),
				('ROM','BAC','Bacau'),
				('AFG','BAD','Badakhshan'),
				('AFG','BAG','Baghlan'),
				('IRQ','BAG','Baghdad'),
				('MMR','BAG','Bago'),
				('AFG','BAH','Badghis'),
				('BRA','BAH','Bahia'),
				('DOM','BAH','Baoruco'),
				('EGY','BAH','Al-Bahr al-Ahmar'),
				('SAU','BAH','Al Bahah'),
				('AZE','BAK','Baki Sahari'),
				('IRN','BAK','ahall va Bakhtiari'),
				('SOM','BAK','Bakool'),
				('AFG','BAL','Balkh'),
				('AZE','BAL','Balakan'),
				('ESP','BAL','Baleares'),
				('IDN','BAL','Bali'),
				('IRN','BAL','a Baluchestan'),
				('PAK','BAL','Balochistan'),
				('TKM','BAL','Balkan'),
				('AFG','BAM','Bamian '),
				('SOM','BAN','Banaadir'),
				('AZE','BAR','Barda'),
				('DOM','BAR','Barahona'),
				('HUN','BAR','Baranya Megye'),
				('IDN','BAR','Kalimantan Barat'),
				('SOM','BAR','Bari'),
				('VEN','BAR','Barinas'),
				('FRA','BAS','Basse-Normandie'),
				('IRQ','BAS','Basrah'),
				('ITA','BAS','Basilicata'),
				('DZA','BAT','Batna'),
				('KHM','BAT','Batdambang'),
				('TCD','BAT','Batha'),
				('SOM','BAY','Bay'),
				('DEU','BB','Brandenburg'),
				('CAN','BC','British Columbia'),
				('MEX','BCN','Baja California'),
				('MEX','BCS','Baja California Sur'),
				('VNM','BDI','Binh Dinh'),
				('PAN','BDT','Bocas del Toro'),
				('DEU','BE','Berlin'),
				('NGA','BE','Benue'),
				('DZA','BEC','Bechar'),
				('CHN','BEJ','Beijing Shi'),
				('DZA','BEJ','Bejaia'),
				('HUN','BEK','Bekes Megye'),
				('BEN','BEL','Belize'),
				('BLZ','BEL','Belize'),
				('AGO','BEN','Benguela'),
				('BOL','BEN','Beni'),
				('IDN','BEN','Bengkulu'),
				('VNM','BEN','Ben Tre'),
				('ALB','BER','Beratit'),
				('TCD','BET','Borkou-Ennedi-Tibesti'),
				('AZE','BEY','Beylaqan'),
				('BTN','BHU','Bhutan'),
				('IND','BIH','Bihar'),
				('ROM','BIH','Bihor'),
				('AZE','BIL','Bilasuvar'),
				('TCD','BIL','Biltine'),
				('TUR','BIL','Bilecik'),
				('BHS','BIM','Bimini Islands'),
				('CHL','BIO','Bio-Bio'),
				('DZA','BIS','Biskra'),
				('ROM','BIS','Bistrita-Nasaud'),
				('HRV','BJE','Bjelovarsko-Bilogorska'),
				('THA','BKM','Bangkok Metropolis'),
				('BGR','BLA','Blagoevgrad'),
				('SWE','BLE','Blekinge lan'),
				('DZA','BLI','Blida'),
				('NGA','BO','Borno'),
				('NIC','BOA','Boaco'),
				('COL','BOG','Bogota'),
				('COL','BOL','Bolivar'),
				('ECU','BOL','Boliar'),
				('VEN','BOL','Bolivar'),
				('PRY','BOQ','Boqueron'),
				('DNK','BOR','Bornholms Amt'),
				('DZA','BOR','Bordj Bou Arreridj'),
				('HUN','BOR','Borsod-Abauj-Zemplen Megye'),
				('ISL','BOR','Borgarfjardharsysla'),
				('BIH','BOS','Bosnia and Herzegovina'),
				('ROM','BOT','Botosani'),
				('COG','BOU','Bouenza'),
				('DZA','BOU','Bouira'),
				('FRA','BOU','Bourgogne'),
				('VNM','BPC','Binh Phuoc'),
				('COG','BRA','Brazzaville'),
				('ROM','BRA','Braila'),
				('BLR','BRE','Brestskaya'),
				('FRA','BRE','Bretagne'),
				('HRV','BRO','Brodsko-Posavska'),
				('ROM','BRS','Brasov'),
				('BRN','BRU','Brunei'),
				('VNM','BRV','Ba Ria-Vung Tau'),
				('EGY','BSA','Bur Sa`id'),
				('EGY','BSU','Bani Suwayf'),
				('VNM','BTH','Binh Thuan'),
				('KWT','BUB','Bubiyan & Warbah'),
				('ROM','BUC','Municipiul Bucuresti'),
				('HUN','BUD','Budapest Fovaros'),
				('BFA','BUF','Burkina Faso'),
				('EGY','BUH','Al-Buhayrah'),
				('AUT','BUR','Burgenland'),
				('BDI','BUR','Burundi'),
				('BGR','BUR','Burgas'),
				('TUR','BUR','Bursa'),
				('NOR','BUS','Buskerud'),
				('UZB','BUX','Buxoro'),
				('ROM','BUZ','Buzau'),
				('GTM','BVE','Baja Verapaz'),
				('DEU','BW','Baden-Wurttemberg'),
				('DEU','BY','Bayern'),
				('PHL','C1','Danao City'),
				('PHL','C2','Dapitan City'),
				('PHL','C3','Davao City'),
				('PHL','C4','Dipolog City'),
				('PHL','C5','Dumaguete City'),
				('PHL','C6','General Santos City'),
				('PHL','C7','Gingoog City'),
				('PHL','C8','Iligan City'),
				('PHL','C9','Iloilo City'),
				('USA','CA','California'),
				('AZE','CAB','Cabrayil'),
				('SLV','CAB','Cabanas'),
				('PER','CAJ','Cajamarca'),
				('AZE','CAL','Calilabad'),
				('ITA','CAL','Calabria'),
				('PER','CAL','Callao'),
				('ROM','CAL','Calarasi'),
				('CMR','CAM','Cameroon'),
				('CUB','CAM','Camaguey'),
				('ITA','CAM','Campania'),
				('MEX','CAM','Campeche'),
				('VNM','CAM','Ca Mau'),
				('ECU','CAN','Canar'),
				('ESP','CAN','Canarias'),
				('PRY','CAN','Canindeyu'),
				('URY','CAN','Canelones'),
				('VNM','CAN','Can Tho'),
				('VNM','CAO','Cao Bang'),
				('CAF','CAR','Central African Republic'),
				('CRI','CAR','Cartago'),
				('ECU','CAR','Carchi'),
				('ESP','CAR','Cantabria'),
				('IRL','CAR','Carlow'),
				('NIC','CAR','Carazo'),
				('ROM','CAR','Caras-Severin'),
				('VEN','CAR','Carabobo'),
				('MAR','CAS','Grand Casablanca'),
				('ARG','CAT','Catamarca'),
				('BHS','CAT','Cat Island'),
				('ESP','CAT','Cataluna'),
				('JAM','CAT','Saint Catherine'),
				('COL','CAU','Cauca'),
				('IRL','CAV','Cavan'),
				('BLZ','CAY','Cayo'),
				('CUB','CDA','Ciego de Avila'),
				('ARG','CDB','Cordoba'),
				('CIV','CDI','Cote D Ivoire'),
				('BRA','CEA','Ceara'),
				('FRA','CEN','Centre'),
				('ISR','CEN','Central District'),
				('KEN','CEN','Central'),
				('PRT','CEN','Centro'),
				('PRY','CEN','Central'),
				('THA','CEN','Central'),
				('ZMB','CEN','Central'),
				('URY','CER','Cerro Largo'),
				('PRY','CGZ','Caaguazu'),
				('ARG','CHA','Chaco'),
				('FRA','CHA','Champagne-Ardenne'),
				('IND','CHA','Chandigarh'),
				('KHM','CHA','Kampong Cham'),
				('SLV','CHA','Chalatenango'),
				('TCD','CHB','Chari-Baguirmi'),
				('KHM','CHH','Kampong Chhnang'),
				('UKR','CHH','Chernihivs ka'),
				('BGD','CHI','Chittagong'),
				('CXR','CHI','Christmas Island'),
				('ECU','CHI','Chimborazo'),
				('JPN','CHI','Chiba'),
				('MEX','CHI','Chihuahua'),
				('MMR','CHI','Chin'),
				('NIC','CHI','Chinandega'),
				('NZL','CHI','Chatham Islands'),
				('PAN','CHI','Chiriqui'),
				('UKR','CHK','Cherkas ka'),
				('DZA','CHL','Chlef'),
				('HND','CHO','Choluteca'),
				('MAR','CHO','Chaouia-Ouardigha'),
				('NIC','CHO','Chontales'),
				('BRB','CHR','Christ Church'),
				('CHN','CHS','Chongqing Shi'),
				('MEX','CHS','Chiapas'),
				('UKR','CHT','Chernivets ka'),
				('ARG','CHU','Chubut'),
				('BOL','CHU','Chuquisaca'),
				('RUS','CI','Chechenskaya'),
				('CUB','CIE','Cienfuegos'),
				('COK','CKI','Cook Islands'),
				('IRL','CLA','Clare'),
				('JAM','CLA','Clarendon'),
				('ESP','CLE','Castilla y Leon'),
				('CUB','CLH','Ciudad de la Habana'),
				('ESP','CLM','Castilla-La Mancha'),
				('ROM','CLU','Cluj'),
				('ESP','CM','Ceuta y Melilla'),
				('GTM','CMT','Chimaltenango'),
				('USA','CO','Colorado'),
				('MEX','COA','Coahuila'),
				('BOL','COC','Cochabamba'),
				('HND','COL','Colon'),
				('MEX','COL','Colima'),
				('PAN','COL','Colon'),
				('URY','COL','Colonia'),
				('COM','COM','Comoros'),
				('HND','COM','Comayagua'),
				('DZA','CON','Constantine'),
				('PRY','CON','Concepcion'),
				('ROM','CON','Constanta'),
				('HND','COP','Copan'),
				('CHL','COQ','Coquimbo'),
				('ARG','COR','Corrientes'),
				('BLZ','COR','Corozal'),
				('FRA','COR','Corse'),
				('IRL','COR','Cork'),
				('PRY','COR','Cordillera'),
				('ECU','COT','Cotopaxi'),
				('ROM','COV','Covasna'),
				('GTM','CQM','Chiquimula'),
				('HUN','CSO','Csongrad Megye'),
				('KEN','CST','Coast'),
				('USA','CT','Connecticut'),
				('COL','CUN','Cundinamarca'),
				('PER','CUS','Cusco'),
				('SLV','CUS','Cuscatlan'),
				('COG','CUV','Cuvette'),
				('CYM','CYN','Cayman Islands'),
				('CYP','CYP','Cyprus'),
				('CZE','CZE','Czech Republic'),
				('PRY','CZP','Caazapa'),
				('PHL','D1','Iriga City'),
				('PHL','D2','La Carlota City'),
				('PHL','D3','Laoag City'),
				('PHL','D4','Lapu-Lapu City'),
				('PHL','D5','Legaspi City'),
				('PHL','D6','Lipa City'),
				('PHL','D7','Lucena City'),
				('PHL','D8','Mandaue City'),
				('PHL','D9','City of Manila'),
				('VNM','DAC','Dac Lak'),
				('IND','DAD','Dadra & Nagar Haveli'),
				('IRQ','DAH','Dahuk'),
				('DOM','DAJ','Dajabon'),
				('SEN','DAK','Dakar'),
				('ISL','DAL','Dalasysla'),
				('SWE','DAL','Dalarnas lan'),
				('ROM','DAM','Dambovita'),
				('VNM','DAN','Da Nang'),
				('EGY','DAQ','Ad-Daqahiyah'),
				('PAN','DAR','Darien'),
				('SYR','DAR','Dar`a'),
				('AZE','DAS','Daskasan'),
				('TKM','DAS','Dasoguz'),
				('AZE','DAV','Davaci'),
				('SYR','DAY','Dayr az Zawr'),
				('USA','DC','District of Columbia'),
				('NGA','DE','Delta'),
				('USA','DE','Delaware'),
				('HUN','DEB','Debrecen Megyei Varos'),
				('IND','DEL','Delhi'),
				('BMU','DEV','Devonshire'),
				('ARG','DF','Distrito Federal'),
				('BRA','DF','Distrito Federal'),
				('MEX','DF','Distrito Federal'),
				('MEX','DGO','Durango'),
				('BGD','DHA','Dhaka'),
				('IRQ','DHI','Dhi Qar'),
				('ALB','DIB','Dibres'),
				('NER','DIF','Diffa'),
				('SYR','DIM','Dimashq'),
				('IRQ','DIY','Diyala'),
				('TUR','DIY','Diyarbakir'),
				('DZA','DJE','Djelfa'),
				('DJI','DJI','Djibouti'),
				('DOM','DN','Distrito Nacional'),
				('VNM','DNA','Dong Nai'),
				('UKR','DNI','Dnipropetrovs ka'),
				('MAR','DOA','Doukkala-Abda'),
				('BGR','DOB','Dobrich'),
				('POL','DOL','Dolnoslaskie'),
				('ROM','DOL','Dolj'),
				('DMA','DOM','Dominica'),
				('IRL','DON','Donegal'),
				('UKR','DON','Donets ka'),
				('VNM','DON','Dong Thap'),
				('NER','DOS','Dosso'),
				('NLD','DRE','Drenthe'),
				('DOM','DUA','Duarte'),
				('HRV','DUB','Dubrovacko-Neretvanska'),
				('IRL','DUB','Dublin'),
				('EGY','DUM','Dumyat'),
				('VNM','DUO','Binh Duong'),
				('ALB','DUR','Durresit'),
				('URY','DUR','Durazno'),
				('PHL','E1','Marawi City'),
				('PHL','E2','Naga City'),
				('PHL','E3','Olongapo City'),
				('PHL','E4','Ormoc City'),
				('PHL','E5','Oroquieta City'),
				('PHL','E6','Ozamis City'),
				('PHL','E7','Pagadian City'),
				('PHL','E8','Palayan City'),
				('PHL','E9','Pasay City'),
				('SLE','EAS','Eastern Province'),
				('ZAF','EAS','Eastern Cape'),
				('ZMB','EAS','Eastern'),
				('JPN','EHI','Ehime'),
				('ALB','ELB','Elbasanit'),
				('DZA','ELB','El Bayadh'),
				('BHS','ELE','Eleuthera'),
				('JAM','ELI','Saint Elizabeth'),
				('DZA','ELO','El Oued'),
				('ITA','EMI','Emilia-Romagna'),
				('GBR','ENG','England'),
				('ECU','EOR','El Oro'),
				('DOM','EPA','Elias Pina'),
				('HND','EPA','El Paraiso'),
				('GTM','EPR','El Progreso'),
				('GNQ','EQG','Equatorial Guinea'),
				('ARG','ERI','Entre Rios'),
				('ERI','ERI','Eritrea'),
				('TUR','ERZ','Erzurum'),
				('BRA','ESA','Espirito Santo'),
				('GTM','ESC','Escuintla'),
				('DOM','ESE','El Seibo'),
				('ECU','ESM','Esmeraldas'),
				('DOM','ESP','Espaillat'),
				('EST','EST','Estonia'),
				('KEN','EST','Eastern'),
				('NIC','EST','Esteli'),
				('ETH','ETH','Ethiopia'),
				('TMP','ETM','East Timor'),
				('EU', 'EU', 'European Union'),
				('ESP','EXT','Extremadura'),
				('BHS','EXU','Exuma & Cays'),
				('ISL','EYJ','Eyjafjardharsysla'),
				('PHL','F1','Puerto Princesa City'),
				('PHL','F2','Quezon City'),
				('PHL','F3','Roxas City'),
				('PHL','F4','San Carlos City'),
				('PHL','F7','San Pablo City'),
				('PHL','F8','Silay City'),
				('PHL','F9','Surigao City'),
				('FLK','FAL','Falkland Islands'),
				('VEN','FAL','Falcon'),
				('AFG','FAR','Farah'),
				('FRO','FAR','Faroe Islands'),
				('KWT','FAR','Al-Farwaniyah'),
				('AFG','FAY','Faryab'),
				('EGY','FAY','Al-Fayyum'),
				('NGA','FC','Abuja'),
				('PAK','FCA','Islamabad Capital Territory'),
				('MAR','FEB','Fes-Boulemane'),
				('HUN','FEJ','Fejer Megye'),
				('GUF','FGU','French Guiana'),
				('MDG','FIA','Fianarantsoa'),
				('ALB','FIE','Fierit'),
				('FJI','FIJ','Fiji'),
				('NOR','FIN','Finnmark'),
				('DNK','FK','Frederiksberg Kommune'),
				('USA','FL','Florida'),
				('NLD','FLE','Flevoland'),
				('URY','FLO','Florida'),
				('USA','FM','Micronesia'),
				('HND','FMO','Francisco Morazan'),
				('ARG','FOR','Formosa'),
				('PYF','FPY','French Polynesia'),
				('FRA','FRA','Franche-Comte'),
				('DNK','FRE','Frederiksborg Amt'),
				('ZAF','FRE','Free State'),
				('ITA','FRI','Friuli-Venezia Giulia'),
				('NLD','FRI','Friesland'),
				('JPN','FUA','Fukuoka'),
				('JPN','FUI','Fukui'),
				('CHN','FUJ','Fujian'),
				('JPN','FUM','Fukushima'),
				('AZE','FUZ','Fuzuli'),
				('DNK','FYN','Fyns Amt'),
				('PHL','G1','Tacloban City'),
				('PHL','G2','Tagaytay City'),
				('PHL','G3','Tagbilaran City'),
				('PHL','G4','Tangub City'),
				('PHL','G5','Toledo City'),
				('PHL','G6','Trece Martires City'),
				('PHL','G7','Zamboanga City'),
				('PHL','G8','Aurora'),
				('USA','GA','Georgia'),
				('BGR','GAB','Gabrovo'),
				('BWA','GAB','Gaborone'),
				('GAB','GAB','Gabon'),
				('AZE','GAD','Gadabay'),
				('HND','GAD','Gracias a Dios'),
				('ECU','GAL','Galapagos'),
				('ESP','GAL','Galicia'),
				('IRL','GAL','Galway'),
				('ROM','GAL','Galati'),
				('GMB','GAM','Gambia'),
				('AZE','GAN','Ganca Sahari'),
				('CHN','GAN','Gansu'),
				('ZAF','GAU','Gauteng'),
				('SWE','GAV','Gavleborgs lan'),
				('BHS','GBA','Grand Bahama'),
				('MAR','GCB','Gharb-Chrarda-Beni Hsen'),
				('SOM','GED','Gedo'),
				('ARM','GEG','Geghark unik i'),
				('NLD','GEL','Gelderland'),
				('BRB','GEO','Saint George'),
				('GEO','GEO','Georgia'),
				('AFG','GHA','Ghazni'),
				('BHR','GHA','Al Mintaqah al Gharbiyah'),
				('DZA','GHA','Ghardaia'),
				('EGY','GHA','Al-Gharbiyah'),
				('GHA','GHA','Ghana'),
				('IRN','GHA','an-e Gharbi'),
				('AFG','GHO','Ghowr'),
				('VNM','GIA','Gia Lai'),
				('GIB','GIB','Gibraltar'),
				('JPN','GIF','Gifu'),
				('VNM','GIN','Bac Giang'),
				('ROM','GIU','Giurgiu'),
				('GRD','GJ','Grenada'),
				('ALB','GJI','Gjirokastres'),
				('GRL','GL','Greenland'),
				('NGA','GO','Gombe'),
				('IND','GOA','Goa'),
				('BRA','GOI','Goias'),
				('AZE','GOR','Goranboy'),
				('ROM','GOR','Gorj'),
				('SWE','GOT','Gotlands lan'),
				('AZE','GOY','Goycay'),
				('CUB','GRA','Granma'),
				('HRV','GRA','Grad Zagreb'),
				('NIC','GRA','Granada'),
				('MEX','GRO','Guerrero'),
				('NLD','GRO','Groningen'),
				('MEX','GTO','Guanajuato'),
				('USA','GU','Guam'),
				('CHN','GUA','Guangdong'),
				('CRI','GUA','Guanacaste'),
				('CUB','GUA','Guantanamo'),
				('ECU','GUA','Guayas'),
				('GLP','GUA','Guadeloupe'),
				('GTM','GUA','Guatemala'),
				('PRY','GUA','Guaira'),
				('VEN','GUA','Guarico'),
				('GNB','GUB','Guinea-Bissau'),
				('DZA','GUE','Guelma'),
				('TCD','GUE','Guera'),
				('CHN','GUI','Guizhou'),
				('GIN','GUI','Guinea'),
				('IND','GUJ','Gujarat'),
				('ISL','GUL','Gullbringusysla'),
				('JPN','GUM','Gunma'),
				('GUY','GUY','Guyana'),
				('CHN','GUZ','Guangxi Zhuangzu'),
				('HUN','GYO','Gyor Megyei Varos'),
				('PHL','H2','Quezon'),
				('PHL','H3','Negros Occidental'),
				('CUB','HAB','La Habana'),
				('AZE','HAC','Haciqabul'),
				('BHR','HAD','Al Hadd'),
				('ISR','HAF','Haifa District'),
				('VNM','HAG','Ha Giang'),
				('BEL','HAI','Hainaut'),
				('CHN','HAI','Hainan'),
				('HTI','HAI','Haiti'),
				('SAU','HAI','Ha il'),
				('HUN','HAJ','Hajdu-Bihar Megye'),
				('TUR','HAK','Hakkari'),
				('SWE','HAL','Hallands lan'),
				('BMU','HAM','Hamilton'),
				('SYR','HAM','Hamah'),
				('VNM','HAM','Ha Nam'),
				('JAM','HAN','Hanover'),
				('VNM','HAN','Ha Tinh'),
				('IND','HAR','Haryana'),
				('ROM','HAR','Harghita'),
				('ZWE','HAR','Harare'),
				('SYR','HAS','Hasakah'),
				('TUR','HAT','Hatay'),
				('VNM','HAT','Ha Tay'),
				('FRA','HAU','Haute-Normandie'),
				('KWT','HAW','Hawalli'),
				('DEU','HB','Bremen'),
				('VNM','HDG','Hai Duong'),
				('DEU','HE','Hessen'),
				('CHN','HEB','Hebei'),
				('NOR','HED','Hedmark'),
				('CHN','HEI','Heilongjiang'),
				('AFG','HEL','Helmand'),
				('CHN','HEN','Henan'),
				('AFG','HER','Herat'),
				('CRI','HER','Heredia'),
				('PAN','HER','Herrera'),
				('HUN','HEV','Heves Megye'),
				('MEX','HGO','Hidalgo'),
				('DEU','HH','Hamburg'),
				('USA','HI','Hawaii'),
				('IND','HIM','Himachal Pradesh'),
				('SYR','HIM','Hims'),
				('JPN','HIR','Hiroshima'),
				('BHS','HIS','Harbour Island & Spanish Wells'),
				('DOM','HMA','Hato Mayor'),
				('VNM','HOA','Hoa Binh'),
				('JPN','HOK','Hokkaido'),
				('CUB','HOL','Holguin'),
				('BLR','HOM','Homyel skaya'),
				('IRN','HOR','n'),
				('NOR','HOR','Hordaland'),
				('BLR','HRO','Hrodzyenskaya'),
				('AGO','HUA','Huambo'),
				('PER','HUA','Huancavelica'),
				('CHN','HUB','Hubei'),
				('SAU','HUD','Al Hudud ash Shamaliyah'),
				('GTM','HUE','Huehuetenango'),
				('CHN','HUN','Hunan'),
				('ROM','HUN','Hunedoara'),
				('PER','HUO','Huanuco'),
				('VNM','HUY','Hung Yen'),
				('JPN','HYO','Hyogo'),
				('USA','IA','Iowa'),
				('ROM','IAL','Ialomita'),
				('ROM','IAS','Iasi'),
				('HND','IBA','Islas de la Bahia'),
				('JPN','IBA','Ibaraki'),
				('PER','ICA','Ica'),
				('TUR','ICE','Icel'),
				('USA','ID','Idaho'),
				('USA','IL','Illinois'),
				('FRA','ILE','Ile-de-France'),
				('ROM','ILF','Ilfov'),
				('DZA','ILL','Illizi '),
				('ECU','IMB','Imbabura'),
				('AZE','IMI','Imisli'),
				('CHN','IMO','Inner Mongolia'),
				('USA','IN','Indiana'),
				('BHS','INA','Inagua'),
				('DOM','IND','Independencia'),
				('HND','INT','Intibuca'),
				('GRC','ION','Ionia Islands'),
				('GRC','IPI','Epirus'),
				('JPN','ISH','Ishikawa'),
				('EGY','ISK','Al-Iskandariyah'),
				('AZE','ISM','Ismayilli'),
				('EGY','ISM','Al-Isma iliyah'),
				('TUR','ISP','Isparta'),
				('HRV','IST','Istarska'),
				('TUR','IST','Istanbul'),
				('PRY','ITA','Itapua'),
				('UKR','IVA','Ivano-Frankivs ka'),
				('JPN','IWA','Iwate'),
				('GTM','IZA','Izabal'),
				('TUR','IZM','Izmir'),
				('GTM','JAL','Jalapa'),
				('MEX','JAL','Jalisco'),
				('BRB','JAM','Saint James'),
				('IDN','JAM','Jambi'),
				('IND','JAM','Jammu & Kashmir'),
				('JAM','JAM','Saint James'),
				('SWE','JAM','Jamtlands lan'),
				('HUN','JAS','Jasz-Nagykun-Szolnok Megye'),
				('SAU','JAW','Al-Jawf'),
				('IDN','JBA','Jawa Barat'),
				('ISR','JER','Jerusalem District'),
				('IND','JHA','Jharkhand'),
				('NGA','JI','Jigawa'),
				('BHR','JID','Jidd Hafs'),
				('CHN','JII','Jiangxi'),
				('CHN','JIN','Jilin'),
				('NIC','JIN','Jinotega'),
				('CHN','JIU','Jiangsu'),
				('EGY','JIZ','Al-Jizah'),
				('SAU','JIZ','Jizan'),
				('UZB','JIZ','Jizzax'),
				('BRB','JOH','Saint John'),
				('MYS','JOH','Johor'),
				('SWE','JON','Jonkopings lan'),
				('JOR','JOR','Jordan'),
				('BRB','JOS','Saint Joseph'),
				('AFG','JOW','Jowzjan'),
				('IDN','JTE','Jawa Tengah'),
				('IDN','JTI','Jawa Timur'),
				('SOM','JUD','Jubbada Dhexe'),
				('SOM','JUH','Jubbada Hoose'),
				('ARG','JUJ','Jujuy'),
				('PER','JUN','Junin'),
				('GTM','JUT','Jutiapa'),
				('CUB','JUV','Isla de la Juventud'),
				('BHR','JUZ','Mintaqat Juzur Hawar'),
				('AFG','KAB','Kabol'),
				('MMR','KAC','Kachin'),
				('JPN','KAG','Kagawa'),
				('TZA','KAG','Kagera'),
				('MMR','KAH','Kayah'),
				('ARM','KAL','Kalininskiy Rayon'),
				('AZE','KAL','Kalbacar'),
				('SWE','KAL','Kalmar lan'),
				('JPN','KAM','Kagoshima'),
				('KHM','KAM','Kampot'),
				('TUR','KAM','Karaman'),
				('AFG','KAN','Kandahar'),
				('JPN','KAN','Kanagawa'),
				('KHM','KAN','Kandal'),
				('MMR','KAN','Kayin'),
				('TCD','KAN','Kanem'),
				('VNM','KAN','Bac Kan'),
				('KHM','KAO','Kaoh Kong'),
				('TWN','KAO','Kao-hsiung'),
				('AFG','KAP','Kapisa'),
				('AUT','KAR','Karnten'),
				('HRV','KAR','Karlovacka'),
				('IND','KAR','Karnataka'),
				('IRQ','KAR','Karbala'),
				('ARM','KAY','K aghak Yerevan'),
				('KAZ','KAZ','Kazakhstan'),
				('NGA','KD','Kaduna'),
				('MYS','KED','Kedah'),
				('MYS','KEL','Kelantan'),
				('IND','KER','Kerala'),
				('BGR','KHA','Khaskovo'),
				('TJK','KHA','Khatlon'),
				('UKR','KHA','Kharkivs ka'),
				('DZA','KHE','Khenchela'),
				('UKR','KHE','Khersons ka'),
				('VNM','KHH','Khanh Hoa'),
				('UKR','KHM','Khmelnyts ka'),
				('BGD','KHU','Khulna'),
				('IRN','KHU','n'),
				('AFG','KHW','Khowst'),
				('IRL','KID','Kildare'),
				('VNM','KIE','Kien Giang'),
				('TZA','KIG','Kigoma'),
				('IRL','KIK','Kilkenny'),
				('TUR','KIL','Kilis'),
				('TZA','KIL','Kilimanjaro'),
				('JAM','KIN','Kingston'),
				('KIR','KIR','Kiribati'),
				('UKR','KIR','Kirovohrads ka'),
				('ISL','KJY','Kjosarsysla'),
				('DNK','KK','Kobenhavns Kommune'),
				('NGA','KN','Kano'),
				('AFG','KNR','Konar'),
				('DNK','KOB','Kobenhavns Amt'),
				('JPN','KOC','Kochi'),
				('TUR','KOC','Kocaeli'),
				('IRN','KOH','eh va Buyer Ahmad'),
				('HUN','KOM','Komarom-Esztergom Megye'),
				('AFG','KON','Kondoz'),
				('TUR','KON','Konya'),
				('VNM','KON','Kon Tum'),
				('HRV','KOP','Koprivnicko-Krizevacka'),
				('ALB','KOR','Korces'),
				('IRN','KOR','n'),
				('ARM','KOT','Kotayk i'),
				('COG','KOU','Kouilou'),
				('HRV','KRA','Krapinsko-Zagorska'),
				('KHM','KRA','Kracheh'),
				('GRC','KRI','Crete'),
				('SWE','KRO','Kronobergs lan'),
				('IRL','KRY','Kerry'),
				('UKR','KRY','Kyrm'),
				('USA','KS','Kansas'),
				('EGY','KSH','Kafr ash-Shaykh'),
				('NGA','KT','Katsina'),
				('POL','KUJ','Kujawsko-Pomorskie'),
				('ALB','KUK','Kukesit'),
				('JPN','KUM','Kumamoto'),
				('AZE','KUR','Kurdamir'),
				('BGR','KUR','Kurdzhali'),
				('KWT','KUW','Al-Kuwayt'),
				('NGA','KW','Kwara'),
				('ZAF','KWA','KwaZulu-Natal'),
				('USA','KY','Kentucky'),
				('PAN','KYA','Kuna Yala'),
				('UKR','KYC','Misto Kyyiv'),
				('JPN','KYO','Kyoto'),
				('KGZ','KYR','Kyrgyzstan'),
				('BGR','KYU','Kyustendil'),
				('UKR','KYY','Kyyivs ka'),
				('NGA','LA','Lagos'),
				('USA','LA','Louisiana'),
				('AZE','LAC','Lacin'),
				('TCD','LAC','Lac'),
				('VNM','LAC','Lao Cai'),
				('SYR','LAD','Ladhiqiyah'),
				('AFG','LAG','Laghman'),
				('CHL','LAG','Los Lagos'),
				('DZA','LAG','Laghouat'),
				('VNM','LAI','Lai Chau'),
				('IND','LAK','Lakshadweep'),
				('DOM','LAL','La Altagracia'),
				('IDN','LAM','Lampung'),
				('PER','LAM','Lambayeque'),
				('VNM','LAM','Lam Dong'),
				('AZE','LAN','Lankaran'),
				('FRA','LAN','Languedoc-Roussillon'),
				('VNM','LAN','Lang Son'),
				('IRL','LAO','Laois'),
				('LAO','LAO','Laos'),
				('BOL','LAP','La Paz'),
				('ESP','LAR','La Rioja'),
				('VEN','LAR','Lara'),
				('AZE','LAS','Lankaran Sahari'),
				('LVA','LAT','Latvia'),
				('URY','LAV','Lavalleja'),
				('ITA','LAZ','Lazio'),
				('POL','LBU','Lubuskie'),
				('LBN','LEB','Lebanon'),
				('TKM','LEB','Lebap'),
				('IRL','LEI','Leitrim'),
				('COG','LEK','Lekoumou'),
				('HND','LEM','Lempira'),
				('NIC','LEO','Leon'),
				('AZE','LER','Lerik'),
				('LSO','LES','Lesotho'),
				('ALB','LEZ','Lezhes'),
				('CHN','LIA','Liaoning'),
				('LBR','LIB','Liberia'),
				('LBY','LIB','Libya'),
				('PER','LIB','La Libertad'),
				('HRV','LIC','Licko-Senjska'),
				('BEL','LIE','Liege'),
				('LIE','LIE','Liechtenstein'),
				('ITA','LIG','Liguria'),
				('COG','LIK','Likouala'),
				('BEL','LIM','Limburg'),
				('CRI','LIM','Limon'),
				('FRA','LIM','Limousin'),
				('IRL','LIM','Limerick'),
				('NLD','LIM','Limburg'),
				('PER','LIM','Lima'),
				('ZAF','LIM','Limpopo'),
				('BHS','LIS','Long Island'),
				('PRT','LIS','Lisboa'),
				('LTU','LIT','Lithuania'),
				('VNM','LIU','Bac Lieu'),
				('SLV','LLI','La Libertad'),
				('TCD','LOC','Logone Occidental'),
				('POL','LOD','Lodzkie'),
				('ECU','LOJ','Loja'),
				('ITA','LOM','Lombardia'),
				('IRL','LON','Longford'),
				('VNM','LON','Long An'),
				('FRA','LOR','Lorraine'),
				('PER','LOR','Loreto'),
				('TCD','LOR','Logone Oriental'),
				('IRL','LOU','Louth'),
				('BGR','LOV','Lovech'),
				('AFG','LOW','Lowgar'),
				('ARG','LPA','La Pampa'),
				('FIN','LPA','Lapplands Lan'),
				('HND','LPA','La Paz'),
				('SLV','LPA','La Paz'),
				('ARG','LRI','La Rioja'),
				('ECU','LRI','Los Rios'),
				('DOM','LRO','La Romana'),
				('PAN','LSA','Los Santos'),
				('AGO','LUA','Luanda'),
				('POL','LUB','Lubelskie'),
				('BRB','LUC','Saint Lucy'),
				('UKR','LUH','Luhans ka'),
				('SLV','LUN','La Union'),
				('AGO','LUS','Lunda Sul'),
				('ZMB','LUS','Lusaka'),
				('BEL','LUX','Luxembourg'),
				('LUX','LUX','Luxembourg'),
				('DOM','LVE','La Vega'),
				('UKR','LVI','Lvivs ka'),
				('USA','MA','Massachusetts'),
				('MAC','MAC','Macau'),
				('MKD','MAC','Macedonia'),
				('ESP','MAD','Madrid'),
				('IND','MAD','Madhya Pradesh'),
				('NIC','MAD','Madriz'),
				('PER','MAD','Madre de Dios'),
				('PRT','MAD','Madeira'),
				('SAU','MAD','Al Madinah'),
				('CHL','MAG','Magallanes y de la Antartica Chilena'),
				('COL','MAG','Magdalena'),
				('MMR','MAG','Magway'),
				('BHR','MAH','Madinat Hamad'),
				('BLR','MAH','Mahilyowskaya'),
				('IND','MAH','Maharashtra'),
				('MDG','MAH','Mahajanga'),
				('TUN','MAH','Mahdia'),
				('BHR','MAI','Madinat `Isa'),
				('GRC','MAK','Macedonia'),
				('SAU','MAK','Makkah'),
				('TCD','MAK','Mayo-Kebbi'),
				('IDN','MAL','Maluku'),
				('MDV','MAL','Maldives'),
				('MLI','MAL','Mali'),
				('MLT','MAL','Malta'),
				('MWI','MAL','Malawi'),
				('POL','MAL','Malopolskie'),
				('URY','MAL','Maldonado'),
				('BHR','MAN','    Al Manamah'),
				('ECU','MAN','Manabi'),
				('IND','MAN','Manipur'),
				('JAM','MAN','Manchester'),
				('MMR','MAN','Mandalay'),
				('NIC','MAN','Managua'),
				('TUR','MAN','Manisa'),
				('BRA','MAR','Maranhao'),
				('ITA','MAR','Marche'),
				('JAM','MAR','Saint Mary'),
				('MTQ','MAR','Martinique'),
				('NER','MAR','Maradi'),
				('PER','MAR','San Martin'),
				('ROM','MAR','Maramures'),
				('SMR','MAR','San Marino'),
				('TKM','MAR','Mary'),
				('AZE','MAS','Masalli'),
				('DZA','MAS','Mascara'),
				('NIC','MAS','Masaya'),
				('SAU','MAS','Al Mintaqah ash Sharqiyah'),
				('CUB','MAT','Matanzas'),
				('NIC','MAT','Matagalpa'),
				('CHL','MAU','Maule'),
				('MRT','MAU','Mauritania'),
				('MUS','MAU','Mauritius'),
				('BHS','MAY','Mayaguana'),
				('IRL','MAY','Mayo'),
				('IRQ','MAY','Maysan'),
				('MYT','MAY','Mayotte'),
				('POL','MAZ','Mazowieckie'),
				('CAN','MB','Manitoba'),
				('ZWE','MBN','Matabeleland North'),
				('ZWE','MBS','Matabeleland South'),
				('DOM','MCR','Monte Cristi'),
				('USA','MD','Maryland'),
				('USA','ME','Maine'),
				('IRL','MEA','Meath'),
				('DZA','MED','Medea'),
				('HRV','MED','Medimurska'),
				('IND','MEG','Meghalaya'),
				('ISR','MEH','Southern District'),
				('ROM','MEH','Mehedinti'),
				('MYS','MEL','Melaka'),
				('ARG','MEN','Mendoza'),
				('VEN','MER','Merida'),
				('CHL','MET','Region Metropolitana'),
				('COL','MET','Meta'),
				('MAR','MET','Meknes-Tafilalt'),
				('MEX','MEX','Mexico'),
				('BRA','MGE','Minas Gerais'),
				('BRA','MGR','Mato Grosso'),
				('BRA','MGS','Mato Grosso do Sul'),
				('USA','MH','Marshall Islands'),
				('USA','MI','Michigan'),
				('BRB','MIC','Saint Michael'),
				('FSM','MIC','Micronesia'),
				('MEX','MIC','Michoacan de Ocampo'),
				('FRA','MID','Midi-Pyrenees'),
				('ZWE','MID','Midlands'),
				('JPN','MIE','Mie'),
				('JPN','MIG','Miyagi'),
				('DZA','MIL','Mila'),
				('AZE','MIN','Mingacevir Sahari'),
				('BLR','MIN','Minskaya'),
				('EGY','MIN','Al-Minya'),
				('VEN','MIR','Miranda'),
				('ARG','MIS','Misiones'),
				('HUN','MIS','Miskolc Megyei Varos'),
				('PRY','MIS','Misiones'),
				('IND','MIZ','Mizoram'),
				('JPN','MIZ','Miyazaki'),
				('TJK','MKB','Mukhtori Kuhistoni Badakhshon'),
				('EGY','MMA','Marsa Matruh'),
				('USA','MN','Minnesota'),
				('EGY','MNF','Al-Minufiyah'),
				('MNG','MNG','Mongolia'),
				('ZWE','MNL','Manicaland'),
				('USA','MO','Missouri'),
				('TCD','MOC','Moyen-Chari'),
				('ITA','MOL','Molise'),
				('MDA','MOL','Moldova'),
				('BGR','MON','Montana'),
				('IRL','MON','Monaghan'),
				('KHM','MON','Mondol Kiri'),
				('MCO','MON','Monaco'),
				('MMR','MON','Mon'),
				('MSR','MON','Montserrat'),
				('URY','MON','Montevideo'),
				('VEN','MON','Monagas'),
				('PER','MOQ','Moquegua'),
				('MEX','MOR','Morelos'),
				('NOR','MOR','More og Romsdal'),
				('SLV','MOR','Morazan'),
				('DZA','MOS','Mostaganem'),
				('MOZ','MOZ','Mozambique'),
				('USA','MP','North Mariana Islands'),
				('DOM','MPL','Monte Plata'),
				('ZAF','MPU','Mpumalanga'),
				('MHL','MRI','Marshall Islands'),
				('USA','MS','Mississippi'),
				('ECU','MSA','Morona-Santiago'),
				('ZWE','MSE','Mashonaland East'),
				('DZA','MSI','M Sila'),
				('DOM','MSN','Monsenor Nouel'),
				('ZWE','MSW','Mashonaland West'),
				('USA','MT','Montana'),
				('MAR','MTH','Marrakech-Tensift-El Haouz'),
				('DOM','MTS','Maria Trinidad Sanchez'),
				('BHR','MUH','Al Muharraq'),
				('ESP','MUR','Murcia'),
				('ROM','MUR','Mures'),
				('IRQ','MUT','Muthanna'),
				('DEU','MV','Mecklenburg-Vorpommern'),
				('ZWE','MVG','Masvingo'),
				('TZA','MWA','Mwanza'),
				('UKR','MYK','Mykolayivs ka'),
				('ISL','MYR','Myrasysla'),
				('NGA','NA','Nassarawa'),
				('DZA','NAA','Naama'),
				('AZE','NAF','Naftalan Sahari'),
				('IND','NAG','Nagaland'),
				('JPN','NAG','Nagano'),
				('KEN','NAI','Nairobi'),
				('IRQ','NAJ','Najaf'),
				('JPN','NAK','Nagasaki'),
				('BEL','NAM','Namur'),
				('NAM','NAM','Namibia'),
				('UZB','NAM','Namangan'),
				('AFG','NAN','Nangarhar'),
				('VNM','NAN','Nam Dinh'),
				('ECU','NAP','Napo'),
				('JPN','NAR','Nara'),
				('NRU','NAU','Nauru'),
				('ESP','NAV','Navarra'),
				('UZB','NAV','Navoiy'),
				('AZE','NAX','Naxcivan Muxtar Respublikasi'),
				('MEX','NAY','Nayarit'),
				('CAN','NB','New Brunswick'),
				('VNM','NBI','Ninh Binh'),
				('NLD','NBR','Noord-Brabant'),
				('USA','NC','North Carolina'),
				('USA','ND','North Dakota'),
				('USA','NE','Nebraska'),
				('KEN','NEA','North Eastern'),
				('ROM','NEA','Neamt'),
				('THA','NEA','Northeastern'),
				('PRY','NEE','Neembucu'),
				('AZE','NEF','Neftcala'),
				('NPL','NEP','Nepal'),
				('VEN','NES','Nueva Esparta'),
				('ARG','NEU','Neuquen'),
				('CAN','NF','Newfoundland'),
				('NFK','NFI','Norfolk Island'),
				('VNM','NGH','Nghe An'),
				('USA','NH','New Hampshire'),
				('NLD','NHL','Noord-Holland'),
				('DEU','NI','Niedersachsen'),
				('NGA','NI','Niger'),
				('COG','NIA','Niari'),
				('NER','NIA','Niamey'),
				('AUT','NIE','Niederosterreich'),
				('TUR','NIG','Nigde'),
				('CHN','NIH','Ningxia Huizu'),
				('VNM','NIH','Bac Ninh'),
				('JPN','NII','Niigata'),
				('AFG','NIM','Nimruz'),
				('IRQ','NIN','Ninawa'),
				('VNM','NIN','Quang Ninh'),
				('GBR','NIR','Northern Ireland'),
				('ISL','NIS','Nordhur-Isafjardharsysla'),
				('NZL','NIS','North Island'),
				('VNM','NIT','Ninh Thuan'),
				('NIU','NIU','Niue'),
				('USA','NJ','New Jersey'),
				('DNK','NJL','Nordjyllands Amt'),
				('MEX','NLN','Nuevo Leon'),
				('USA','NM','New Mexico'),
				('ISL','NMU','Nordhur-Mulasysla'),
				('HUN','NOG','Nograd Megye'),
				('FRA','NOR','Nord-Pas-de-Calais'),
				('NOR','NOR','Nordland'),
				('PRT','NOR','Norte'),
				('SLE','NOR','Northern Province'),
				('SWE','NOR','Norrbottens lan'),
				('THA','NOR','Northern'),
				('ZAF','NOR','Northern Cape'),
				('BHS','NPR','New Providence'),
				('ZAF','NRW','North-West'),
				('CAN','NS','Nova Scotia'),
				('NIC','NSE','Nueva Segovia'),
				('AUS','NSW','New South Wales'),
				('CAN','NT','Northwest Territories'),
				('ANT','NTA','Netherlands Antilles'),
				('IDN','NTB','Nusa Tenggara Barat'),
				('NOR','NTR','Nord-Trondelag'),
				('IDN','NTT','Nusa Tenggara Timur'),
				('AUS','NTY','Northern Territory'),
				('ISL','NTY','Nordhur-Thingeyjarsysla'),
				('CAN','NU','Nunavut'),
				('AFG','NUR','Nurestan'),
				('USA','NV','Nevada'),
				('DEU','NW','Nordrhein-Westfalen'),
				('NCL','NWC','New Caledonia'),
				('PAK','NWF','North-West Frontier Province'),
				('USA','NY','New York'),
				('KEN','NYA','Nyanza'),
				('MEX','OAX','Oaxaca'),
				('AUT','OBE','Oberosterreich'),
				('HND','OCO','Ocotepeque'),
				('UKR','ODE','Odes ka'),
				('IRL','OFF','Offaly'),
				('NOR','OFO','Ostfold'),
				('NGA','OG','Ogun'),
				('AZE','OGU','Oguz'),
				('USA','OH','Ohio'),
				('JPN','OIT','Oita'),
				('USA','OK','Oklahoma'),
				('JPN','OKA','Okayama'),
				('JPN','OKI','Okinawa'),
				('HND','OLA','Olancho'),
				('ROM','OLT','Olt'),
				('OMN','OMN','Oman'),
				('CAN','ON','Ontario'),
				('BEL','OOV','Oost-Vlaanderen'),
				('POL','OPO','Opolskie'),
				('NOR','OPP','Oppland'),
				('USA','OR','Oregon'),
				('BLZ','ORA','Orange Walk'),
				('DZA','ORA','Oran'),
				('ECU','ORE','Orellana'),
				('SWE','ORE','Orebro lan'),
				('IND','ORI','Orissa'),
				('AFG','ORU','Oruzgan'),
				('BOL','ORU','Oruro'),
				('JPN','OSA','Osaka'),
				('HRV','OSJ','Osjecko-Baranjska'),
				('NOR','OSL','Oslo'),
				('FIN','OST','Ostra Finlands Lan'),
				('SWE','OST','Ostergotlands lan'),
				('DZA','OUA','Ouargla'),
				('TCD','OUA','Ouaddai'),
				('DZA','OUM','Oum el Bouaghi'),
				('NLD','OVE','Overijssel'),
				('NGA','OY','Oyo'),
				('USA','PA','Pennsylvania'),
				('BMU','PAG','Paget'),
				('MYS','PAH','Pahang'),
				('ESP','PAI','Pais Vasco'),
				('AFG','PAK','Paktika'),
				('PLW','PAL','Palau'),
				('BOL','PAN','Pando'),
				('PAN','PAN','Panama'),
				('IDN','PAP','Papua'),
				('AFG','PAR','Parvan'),
				('BRA','PAR','Para'),
				('PRY','PAR','Paraguari'),
				('ECU','PAS','Pastaza'),
				('PER','PAS','Pasco'),
				('FRA','PAY','Pays-de-la Loire'),
				('URY','PAY','Paysandu'),
				('BGR','PAZ','Pazardzhik'),
				('POL','PDK','Podkarpackie'),
				('CAN','PE','Prince Edward Island'),
				('HUN','PEC','Pecs Megyei Varos'),
				('DOM','PED','Pedernales'),
				('GRC','PEL','Peloponnesus'),
				('BMU','PEM','Pembroke'),
				('BGR','PER','Pernik'),
				('BRA','PER','Pernambuco'),
				('DOM','PER','Peravia'),
				('MYS','PER','Perak'),
				('HUN','PES','Pest Megye'),
				('MYS','PES','Perlis'),
				('BRB','PET','Saint Peter'),
				('GTM','PET','Peten'),
				('PRY','PHA','Presidente Hayes'),
				('VNM','PHC','Thanh Pho Ho Chi Minh'),
				('BRB','PHI','Saint Philip'),
				('VNM','PHP','Thanh Pho Hai Phong'),
				('VNM','PHU','Phu Yen'),
				('BRA','PIA','Piaui'),
				('ECU','PIC','Pichincha'),
				('FRA','PIC','Picardie'),
				('ITA','PIE','Piemonte'),
				('CUB','PIN','Pinar del Rio'),
				('MYS','PIN','Pulau Pinang'),
				('PCN','PIT','Pitcairn Islands'),
				('PER','PIU','Piura'),
				('AFG','PKT','Paktia'),
				('NGA','PL','Plateau'),
				('COG','PLA','Plateaux'),
				('BGR','PLE','Pleven'),
				('BGR','PLO','Plovdiv'),
				('PNG','PNG','Papua New Guinea'),
				('POL','POD','Podlaskie'),
				('FRA','POI','Poitou-Charentes'),
				('UKR','POL','Poltavs ka'),
				('POL','POM','Pomorskie'),
				('IND','PON','Pondicherry'),
				('COG','POO','Pool'),
				('JAM','POR','Portland'),
				('BOL','POT','Potosi'),
				('KHM','POU','Pouthisat'),
				('HRV','POZ','Pozesko-Slavonska'),
				('DOM','PPL','Puerto Plata'),
				('USA','PR','Puerto Rico'),
				('ROM','PRA','Prahova'),
				('BRA','PRB','Paraiba'),
				('KHM','PRE','Preah Vihear'),
				('HRV','PRI','Primorsko-Goranska'),
				('BRA','PRN','Parana'),
				('FRA','PRO','Provence-Alpes-Cote d`Azur'),
				('KHM','PRV','Prey Veng'),
				('VNM','PTO','Phu Tho'),
				('MEX','PUE','Puebla'),
				('ITA','PUG','Puglia'),
				('CRI','PUN','Puntarenas'),
				('IND','PUN','Punjab'),
				('PAK','PUN','Punjab'),
				('PER','PUN','Puno'),
				('USA','PW','Palau'),
				('AZE','QAB','Qabala'),
				('IRQ','QAD','Qadisiyah'),
				('EGY','QAH','Al-Qahirah'),
				('EGY','QAL','Al-Qalyubyah'),
				('SAU','QAS','Al Qasim'),
				('UZB','QAS','Qashqadaryo'),
				('AZE','QAX','Qax'),
				('AZE','QAZ','Qazax'),
				('VNM','QBI','Quang Binh'),
				('CAN','QC','Quebec'),
				('CHN','QIN','Qinghai'),
				('EGY','QIN','Qina'),
				('AUS','QLD','Queensland'),
				('VNM','QNG','Quang Ngai'),
				('VNM','QNM','Quang Nam'),
				('AZE','QOB','Qobustan'),
				('UZB','QOR','Qoraqalpog`iston'),
				('MEX','QRO','Queretaro de Arteaga'),
				('MEX','QTR','Quintana Roo'),
				('QAT','QTR','Qatar'),
				('VNM','QTR','Quang Tri'),
				('AZE','QUB','Quba'),
				('GTM','QUE','Quetzaltenango'),
				('GTM','QUI','Quiche'),
				('AZE','QUL','Qubadli'),
				('AZE','QUS','Qusar'),
				('BHS','RAG','Ragged Islands'),
				('BGD','RAJ','Rajshahi'),
				('IND','RAJ','Rajasthan'),
				('MMR','RAK','Rakhine'),
				('BGR','RAZ','Razgrad'),
				('BRA','RDJ','Rio de Janeiro'),
				('REU','RE','Reunion'),
				('DZA','REL','Relizane'),
				('GTM','RET','Retalhuleu'),
				('BRA','RGN','Rio Grande do Norte'),
				('BRA','RGS','Rio Grande do Sul'),
				('FRA','RHO','    Rhooe-Alpes'),
				('USA','RI','Rhode Island'),
				('IDN','RIA','Riau'),
				('DNK','RIB','Ribe Amt'),
				('BHR','RIF','Ar Rifa` wa al Mintaqah al Janubiyah'),
				('DNK','RIN','Ringkobing Amt'),
				('NIC','RIV','Rivas'),
				('UKR','RIV','Rivnens ka'),
				('URY','RIV','Rivera'),
				('SAU','RIY','Ar Riyad'),
				('ARG','RNE','Rio Negro'),
				('URY','RNE','Rio Negro'),
				('ISL','RNG','Rangarvallasysla'),
				('URY','ROC','Rocha'),
				('NOR','ROG','Rogaland'),
				('BRA','RON','Rondonia'),
				('BRA','ROR','Roraima'),
				('DNK','ROS','Roskilde Amt'),
				('IRL','ROS','Roscommon'),
				('KHM','ROT','Rotanah Kiri'),
				('DEU','RP','Rheinland-Pfalz'),
				('NIC','RSJ','Rio San Juan'),
				('MAR','RSZ','Rabat-Sale-Zemmour-Zaer'),
				('TZA','RUK','Rukwa'),
				('BGR','RUS','Ruse'),
				('KEN','RVY','Rift Valley'),
				('RWA','RWA','Rwanda'),
				('AZE','SAA','Saatli'),
				('AZE','SAB','Sabirabad'),
				('MYS','SAB','Sabah'),
				('GTM','SAC','Sacatepequez'),
				('JPN','SAG','Saga'),
				('MMR','SAG','Sagaing'),
				('DZA','SAI','Saida'),
				('JPN','SAI','Saitama'),
				('AZE','SAK','Saki'),
				('ARG','SAL','Salta'),
				('AUT','SAL','Salzburg'),
				('AZE','SAL','Salyan'),
				('DOM','SAL','Salcedo'),
				('IRQ','SAL','Salah ad Din'),
				('ROM','SAL','Salaj'),
				('TCD','SAL','Salamat'),
				('URY','SAL','Salto'),
				('AFG','SAM','Samangan'),
				('AZE','SAM','Samaxi'),
				('DOM','SAM','Samana'),
				('UZB','SAM','Samarqand'),
				('WSM','SAM','Samoa'),
				('BMU','SAN','Sandys'),
				('BOL','SAN','Santa Cruz'),
				('COG','SAN','Sangha'),
				('COL','SAN','Santander'),
				('CUB','SAN','Santiago de Cuba'),
				('DOM','SAN','Santiago'),
				('SLV','SAN','Santa Ana'),
				('STP','SAO','Sao Tome & Principe'),
				('AFG','SAR','Sar-e Pol'),
				('AZE','SAR','Samkir'),
				('ITA','SAR','Sardegna'),
				('MYS','SAR','Sarawak'),
				('AZE','SAS','Saki Sahari'),
				('ROM','SAT','Satu Mare'),
				('AUS','SAU','South Australia'),
				('EGY','SAW','Sawhaj'),
				('AZE','SAX','Samux'),
				('HND','SBA','Santa Barbara'),
				('IDN','SBA','Sumatera Barat'),
				('USA','SC','South Carolina'),
				('BRA','SCA','Santa Catarina'),
				('GBR','SCO','Scotland'),
				('ARG','SCR','Santa Cruz'),
				('DOM','SCR','San Cristobal'),
				('USA','SD','South Dakota'),
				('ARG','SDE','Santiago del Estero'),
				('GRC','SEE','Central Greece & Evvoia'),
				('IDN','SEL','Kalimantan Selatan'),
				('MYS','SEL','Selangor'),
				('MYS','SEM','Sembilan'),
				('BRA','SER','Sergipe'),
				('DZA','SET','Setif'),
				('UKR','SEV','Misto Sevastopol'),
				('SYC','SEY','Seychelles'),
				('ARG','SFE','Santa Fe'),
				('BGR','SFG','Sofiya-Grad'),
				('BMU','SGS','Saint Georges'),
				('DEU','SH','Schleswig-Holstein'),
				('BHR','SHA','Al Mintaqah ash Shamaliyah'),
				('EGY','SHA','Al-Sharqiyah'),
				('IRN','SHA','an-e Sharqi'),
				('MMR','SHA','Shan'),
				('CHN','SHG','Shandong'),
				('JPN','SHG','Shiga'),
				('SOM','SHH','Shabeellaha Hoose'),
				('ARM','SHI','Shiraki'),
				('CHN','SHI','Shanxi'),
				('TZA','SHI','Shinyanga'),
				('ALB','SHK','Shkodres'),
				('JPN','SHM','Shimane'),
				('ISL','SHN','Snaefellsnessysla- og Hnappadalssysla'),
				('BGR','SHU','Shumen'),
				('CHN','SHX','Shaanxi'),
				('JPN','SHZ','Shizuoka'),
				('HRV','SIB','Sibensko-Kninska'),
				('ROM','SIB','Sibiu'),
				('CHN','SIC','Sichuan'),
				('ITA','SIC','Sicilia'),
				('DZA','SID','Sidi Bel Abbes'),
				('KHM','SIE','Siem Reab'),
				('IND','SIK','Sikkim'),
				('BGR','SIL','Silistra'),
				('MEX','SIN','Sinaloa'),
				('PAK','SIN','Sind'),
				('TUR','SIR','Sirnak'),
				('UZB','SIR','Sirdaryo'),
				('HRV','SIS','Sisacko-Moslavacka'),
				('NZL','SIS','South Island'),
				('BHR','SIT','Sitrah'),
				('TUR','SIV','Sivas'),
				('AZE','SIY','Siyazan'),
				('EGY','SJA','    Sina` al-Janubiya'),
				('DNK','SJL','Sonderjyllands Amt'),
				('CRI','SJO','San Jose'),
				('URY','SJO','San Jose'),
				('ARG','SJU','San Juan'),
				('DOM','SJU','San Juan'),
				('CAN','SK','Saskatchewan'),
				('ISL','SKA','Skagafjardharsysla'),
				('SWE','SKA','Skane lan'),
				('DZA','SKI','Skikda'),
				('KNA','SKN','Saint Kitts & Nevis'),
				('DEU','SL','Saarland'),
				('POL','SLA','Slaskie'),
				('LCA','SLC','Saint Lucia'),
				('BGR','SLI','Sliven'),
				('IRL','SLI','Sligo'),
				('SVK','SLO','Slovakia'),
				('SVN','SLO','Slovenia'),
				('MEX','SLP','San Luis Potosi'),
				('ARG','SLU','San Luis'),
				('IDN','SLU','Sulawesi Utara'),
				('GTM','SMA','San Marcos'),
				('MAR','SMD','Sous-Massa-Draa'),
				('BMU','SMI','Smiths'),
				('SLV','SMI','San Miguel'),
				('BGR','SMO','Smolyan'),
				('ISL','SMU','Sudhur-Mulasysla'),
				('DEU','SN','Sachsen'),
				('SGP','SNG','Singapore'),
				('NGA','SO','Sokoto'),
				('VNM','SOC','Soc Trang'),
				('FIN','SOD','Sodra Finlands Lan'),
				('SWE','SOD','Sodermanlands lan'),
				('BGR','SOF','Sofiya'),
				('NOR','SOF','Sogn og Fjordane'),
				('GTM','SOL','Solola'),
				('SLB','SOL','Solomon Islands'),
				('VNM','SOL','Son La'),
				('HUN','SOM','Somogy Megye'),
				('MEX','SON','Sonora'),
				('SLV','SON','Sonsonate'),
				('URY','SOR','Soriano'),
				('BMU','SOU','Southampton'),
				('SLE','SOU','Southern Province'),
				('THA','SOU','Southern'),
				('TUN','SOU','Sousse'),
				('ZMB','SOU','Southern'),
				('BRA','SPA','Sao Paulo'),
				('PRY','SPE','San Pedro'),
				('HRV','SPL','Splitsko-Dalmatinska'),
				('DOM','SPM','San Pedro de Macoris'),
				('SPM','SPM','Saint Pierre & Miquelon'),
				('KHM','SPO','Kampong Spoe'),
				('DOM','SRA','Sanchez Ramirez'),
				('LKA','SRI','Sri Lanka'),
				('DOM','SRO','Santiago Rodriguez'),
				('GTM','SRO','Santa Rosa'),
				('BIH','SRP','Republika Srpska'),
				('SLV','SSA','San Salvador'),
				('IDN','SSE','Sulawesi Selatan'),
				('EGY','SSH','Sina` ash-Shamaliyah'),
				('CUB','SSP','Sancti Spiritus'),
				('DEU','ST','Sachsen-Anhalt'),
				('BGR','STA','Stara Zagora'),
				('BLZ','STA','Stann Creek'),
				('AUT','STE','Steiermark'),
				('IDN','STE','Sulawesi Tengah'),
				('IDN','STG','Sulawesi Tenggara'),
				('SHN','STH','Saint Helena'),
				('ISL','STI','Sudhur-Thingeijjar'),
				('NZL','STI','Stewart Island'),
				('SEN','STL','Saint-Louis'),
				('DNK','STO','Storstroms Amt'),
				('KHM','STO','Stoeng Treng'),
				('SWE','STO','Stockholms lan'),
				('ISL','STR','Strandasysla'),
				('NOR','STR','Sor-Trondelag'),
				('VCT','STV','Saint Vincent & the Grenadines'),
				('ECU','SUC','Sucumbios'),
				('GTM','SUC','Suchitepequez'),
				('ROM','SUC','Suceava'),
				('VEN','SUC','Sucre'),
				('SDN','SUD','Sudan'),
				('TJK','SUG','Sughd'),
				('IRQ','SUL','Sulaymaniyah'),
				('UKR','SUM','Sums ka'),
				('AZE','SUR','Susa'),
				('SUR','SUR','Suriname'),
				('UZB','SUR','Surxondaryo'),
				('IDN','SUT','Sumatera Utara'),
				('EGY','SUW','Al-Suways'),
				('KHM','SVA','Svay Rieng'),
				('SLV','SVI','San Vicente'),
				('SJM','SVL','Svalbard'),
				('POL','SWI','Swietokrzyskie'),
				('CHE','SWZ','Switzerland'),
				('SWZ','SWZ','Swaziland'),
				('ARM','SYU','Syunik i'),
				('HUN','SZA','Szabolcs-Szatmar-Bereg Megye'),
				('HUN','SZE','Szeged Megyei Varos'),
				('PAK','TA','Federally Administered Tribal Areas'),
				('MEX','TAB','Tabasco'),
				('SAU','TAB','Tabuk'),
				('TZA','TAB','Tabora'),
				('PER','TAC','Tacna'),
				('URY','TAC','Tacuarembo'),
				('VEN','TAC','Tachira'),
				('NER','TAH','Tahoua'),
				('AFG','TAK','Takhar'),
				('KHM','TAK','Takev'),
				('DZA','TAM','Tamanghasset'),
				('IND','TAM','Tamil Nadu'),
				('IRQ','TAM','Ta`mim'),
				('MEX','TAM','Tamaulipas'),
				('MMR','TAN','Tanintharyi'),
				('TCD','TAN','Tandjile'),
				('AZE','TAR','Tartar'),
				('BOL','TAR','Tarija'),
				('CHL','TAR','Tarapaca'),
				('AUS','TAS','Tasmania'),
				('MAR','TAT','Tanger-Tetouan'),
				('ARM','TAV','Tavushi'),
				('VNM','TAY','Tay Ninh'),
				('ARG','TDF','Tierra del Fuego'),
				('VNM','TDH','Thu Do Ha Noi'),
				('DZA','TEB','Tebessa'),
				('ISR','TEL','Tel Aviv District'),
				('NOR','TEL','Telemark'),
				('ROM','TEL','Teleorman'),
				('IDN','TEN','Kalimantan Tengah'),
				('MYS','TER','Terengganu'),
				('UKR','TER','Ternopils ka'),
				('VNM','TGI','Tien Giang'),
				('DEU','TH','Thuringen'),
				('VNM','THB','Thai Binh'),
				('GRC','THE','Thessalia'),
				('VNM','THH','Thanh Hoa'),
				('SEN','THI','Thies'),
				('BRB','THO','Saint Thomas'),
				('JAM','THO','Saint Thomas'),
				('GRC','THR','Thrace'),
				('MAR','THT','Taza-Al Hoceima-Taounate'),
				('KHM','THU','Kampong Thum'),
				('DZA','TIA','Tiaret'),
				('CHN','TIB','Tibet'),
				('NER','TIL','Tillaberi'),
				('IDN','TIM','Kalimantan Timur'),
				('ROM','TIM','Timis'),
				('DZA','TIN','Tindouf'),
				('DZA','TIP','Tipaza'),
				('IRL','TIP','Tipperary'),
				('ALB','TIR','Tiranes'),
				('AUT','TIR','Tirol'),
				('DZA','TIS','Tissemsilt'),
				('DZA','TIZ','Tizi Ouzou'),
				('MEX','TLA','Tlaxcala'),
				('DZA','TLE','Tlemcen'),
				('USA','TN','Tennessee'),
				('TON','TNG','Tonga'),
				('VNM','TNY','Thai Nguyen'),
				('MDG','TOA','Toamasina'),
				('BRA','TOC','Tocantins'),
				('JPN','TOC','Tochigi'),
				('TGO','TOG','Togo'),
				('JPN','TOK','Tokushima'),
				('TKL','TOK','Tokelau'),
				('BLZ','TOL','Toledo'),
				('HUN','TOL','Tolna Megye'),
				('MDG','TOL','Toliary'),
				('ITA','TOS','Toscana'),
				('UZB','TOS','Toshkent'),
				('GTM','TOT','Totonicapan'),
				('JPN','TOT','Tottori'),
				('AZE','TOV','Tovuz'),
				('JPN','TOY','Tokyo'),
				('TWN','TPS','Tai-pei'),
				('VNM','TRA','Tra Vinh'),
				('ITA','TRE','Trentino-Alto Adige'),
				('JAM','TRE','Trelawny'),
				('IND','TRI','Tripura'),
				('NOR','TRO','Troms'),
				('TTO','TRT','Trinidad & Tobago'),
				('VEN','TRU','Trujillo'),
				('UZB','TSH','Toshkent Shahri'),
				('VNM','TTH','Thua Thien-Hue'),
				('ARG','TUC','Tucuman'),
				('TCA','TUK','Turks & Caicos Islands'),
				('ROM','TUL','Tulcea'),
				('PER','TUM','Tumbes'),
				('CUB','TUN','Las Tunas'),
				('TUN','TUN','Tunis'),
				('BGR','TUR','Turgovishte'),
				('TUV','TUV','Tuvalu'),
				('VNM','TUY','Tuyen Quang'),
				('TWN','TWS','Tai-wan'),
				('USA','TX','Texas'),
				('JPN','TYM','Toyama'),
				('URY','TYT','Treinta y Tres'),
				('ARE','UAE','United Arab Emirates'),
				('IND','UAR','Uttaranchal'),
				('AZE','UCA','Ucar'),
				('PER','UCA','Ucayali'),
				('UGA','UGA','Uganda'),
				('FIN','ULE','Uleaborgs Lan'),
				('USA','UM','Minor Outlying Islands'),
				('ITA','UMB','Umbria'),
				('AFG','UNK','Unknown'),
				('BEL','UNK','Unknown'),
				('BEN','UNK','Unknown'),
				('BIH','UNK','Unknown'),
				('BLR','UNK','Unknown'),
				('BWA','UNK','Unknown'),
				('CHN','UNK','Unknown'),
				('FRA','UNK','Unknown'),
				('IDN','UNK','Unknown'),
				('IRL','UNK','Unknown'),
				('KHM','UNK','Unknown'),
				('MMR','UNK','Unknown'),
				('MYS','UNK','Unknown'),
				('NGA','UNK','Gongola'),
				('ROM','UNK','Unknown'),
				('SYR','UNK','Unknown'),
				('TJK','UNK','Unknown'),
				('TUN','UNK','Unknown'),
				('TZA','UNK','Unknown'),
				('UZB','UNK','Unknown'),
				('ZAF','UNK','Unknown'),
				('ZMB','UNK','Unknown'),
				('ZWE','UNK','Unknown'),
				('SWE','UPP','Uppsala lan'),
				('SLV','USU','Usulutan'),
				('USA','UT','Utah'),
				('NLD','UTR','Utrecht'),
				('IND','UTT','Uttar Pradesh'),
				('USA','VA','Virginia'),
				('NOR','VAG','Vest-Agder'),
				('CHL','VAL','Valparaiso'),
				('COL','VAL','Valle del Cauca'),
				('DOM','VAL','Valverde'),
				('ESP','VAL','Valencia'),
				('HND','VAL','SValle'),
				('ROM','VAL','Valcea'),
				('VUT','VAN','Vanuatu'),
				('AFG','VAR','Vardak'),
				('BGR','VAR','Varna'),
				('HRV','VAR','Varazdinska'),
				('SWE','VAR','Varmlands lan'),
				('VEN','VAR','Vargas'),
				('FIN','VAS','Vastra Finlands Lan'),
				('HUN','VAS','Vas Megye'),
				('ROM','VAS','Vaslui'),
				('SWE','VAS','Vasterbottens lan'),
				('ARM','VAY','Vayots Dzori'),
				('ISL','VBA','Vestur-Bardhastrandarsysla'),
				('ITA','VDA','Valle d Aosta'),
				('DNK','VEJ','Vejle Amt'),
				('BGR','VEL','Veliko Turnovo'),
				('ITA','VEN','Veneto'),
				('MEX','VER','Veracruz-Llave'),
				('PAN','VER','Veraguas'),
				('HUN','VES','Veszprem Megye'),
				('NOR','VFO','Vestfold'),
				('SWE','VGI','Vastra Gotalands lan'),
				('ISL','VHU','Vestur-Hunavatnssysla'),
				('USA','VI','Virgin Islands'),
				('DNK','VIB','Viborg Amt'),
				('AUS','VIC','Victoria'),
				('BGR','VID','Vidin'),
				('CUB','VIL','Villa Clara'),
				('VNM','VIL','Vinh Long'),
				('UKR','VIN','Vinnyts ka'),
				('HRV','VIR','Viroviticko-Podravska'),
				('ISL','VIS','Vestur-Isafjardharsysla'),
				('BLR','VIT','Vitsyebskaya'),
				('ALB','VLO','Vlores'),
				('SWE','VML','Vastmanlands lan'),
				('SWE','VNL','Vasternorrlands lan'),
				('UKR','VOL','Volyns ka'),
				('AUT','VOR','Vorarlberg'),
				('VNM','VPC','Vinh Phuc'),
				('BGR','VRA','Vratsa'),
				('ROM','VRA','Vrancea'),
				('ISL','VSK','Vestur-Skaftafellssysla'),
				('DNK','VSL','Vestsjaellands Amt'),
				('USA','VT','Vermont'),
				('HRV','VUK','Vukovarsko-Srijemska'),
				('USA','WA','Washington'),
				('WLF','WAF','Wallis & Futuna'),
				('JPN','WAK','Wakayama'),
				('GBR','WAL','Wales'),
				('BMU','WAR','Warwick'),
				('POL','WAR','Warminsko-Mazurskie'),
				('IRQ','WAS','Wasit'),
				('IRL','WAT','Waterford'),
				('AUS','WEA','Western Australia'),
				('IND','WES','West Bengal'),
				('IRL','WES','Westmeath'),
				('SLE','WES','Western Area'),
				('ZAF','WES','Western Cape'),
				('ZMB','WES','Western'),
				('BEL','WEV','West-Vlaanderen'),
				('IRL','WEX','Wexford'),
				('USA','WI','Wisconsin'),
				('IRL','WIC','Wicklow'),
				('AUT','WIE','Wien'),
				('POL','WIE','Wielkopolskie'),
				('MYS','WIL','Wilayah Persekutuan'),
				('EGY','WJA','Al-Wadi al-Jadid'),
				('JAM','WML','Westmoreland'),
				('KEN','WST','Western'),
				('BHR','WUS','Al Mintaqah al Wusta'),
				('USA','WV','West Virginia'),
				('USA','WY','Wyoming'),
				('AZE','XAC','Xacmaz'),
				('AZE','XAL','Xanlar'),
				('AZE','XAN','Xankandi Sahari'),
				('CHN','XIU','Xinjiang Uygur'),
				('AZE','XIZ','Xizi'),
				('AZE','XOC','Xocali'),
				('UZB','XOR','Xorazm'),
				('AZE','XOV','Xocavand'),
				('TUR','YAL','Yalova'),
				('BGR','YAM','Yambol'),
				('AZE','YAR','Yardimli'),
				('VEN','YAR','Yaracuy'),
				('YEM','YEM','Yemen'),
				('VNM','YEN','Yen Bai'),
				('AZE','YES','Yevlax Sahari'),
				('AZE','YEV','Yevlax'),
				('JPN','YMG','Yamaguchi'),
				('JPN','YMN','Yamanashi'),
				('JPN','YMT','Yamagata'),
				('IDN','YOG','Yogyakarta'),
				('HND','YOR','Yoro'),
				('CAN','YT','Yukon'),
				('MEX','YUC','Yucatan'),
				('CHN','YUN','Yunnan'),
				('NGA','ZA','Zamfara'),
				('AFG','ZAB','Zabol'),
				('GTM','ZAC','Zacapa'),
				('MEX','ZAC','Zacatecas'),
				('POL','ZAC','Zachodniopomorskie'),
				('HRV','ZAG','Zagrebacka'),
				('UKR','ZAK','Zakarpats ka'),
				('HUN','ZAL','Zala Megye'),
				('AZE','ZAN','Zangilan'),
				('UKR','ZAP','Zaporiz ka'),
				('AZE','ZAQ','Zaqatala'),
				('AZE','ZAR','Zardab'),
				('ECU','ZCH','Zamora-Chinchipe'),
				('NLD','ZEE','Zeeland'),
				('CHN','ZHE','Zhejiang'),
				('NLD','ZHO','Zuid-Holland'),
				('UKR','ZHY','Zhytomyrs ka'),
				('NER','ZIN','Zinder'),
				('VEN','ZUL','Zulia'),
				('CHN','SHA','Shanghai Shi'),
				('CHN','TIA','Tianjin Shi');
EOD;
$wpdb->query($sql);
