<!-- BEGIN: page -->
<div class="pw-pharmacy-wrap page-search-summary pw-search-conditions">
	<!-- Start page content here -->

	<!-- BEGIN: headings -->
	<p>Select the medical condition from the list below to see medications used to treat this condition.</p>
	<!-- END: headings -->

	{SEARCH_SUMMARYHEADING}
	{SEARCH_SUMMARYTEXT}
	<!-- BEGIN: showconditions -->
	<ul class="condition_items">
		<!-- BEGIN: condition -->
		<li><a class="condition" href="{CONDITION_LINK}">{CONDITION_ITEM}</a></li>
		<!-- END: condition -->
	</ul>
	<!-- END: showconditions -->

	<!-- End page content here -->
</div>
<!-- END: page -->