<!-- BEGIN: page -->
<div class="pharmacy-report-wrap pw-search-summary">
	<div>{RESULT_MESSAGES}</div>
	<form name="frmReport" id="frmReport" method="post">
		<input type="hidden" name="hdReportType" value="{report_type}" />
		{REPORT_TABLE}
		<div class="rpfooter">
			<input type="submit" class="button" name="btReport" value="{REPORT_BUTTON}" />
		</div>
		<!-- page-search-detail ends -->
	</form>
</div>
<!-- END: page -->