<!-- BEGIN: page -->
<div class="pw-pharmacy-wrap pw-change-password container">
	<!-- BEGIN: CHANGEPASS -->
	<div class="change-password large-6 small-12 columns">
		{RESULT_MESSAGES}
		<p class="change-password-message">Please change your password and log in again before continuing.</p>
		<form id="frmChangePassword" name="frmChangePassword" method="post">
			<div class="row">
				<div class="large-12 columns">
					<label><strong>Current Password</strong></label>
					<input type="Password" size="20" value="{VALUE_OLDPASS}" name="oldpass" id="oldpass" autocomplete="current-password" />
					{ERROR_CURRENTPASS}
				</div>
			</div>
			<div class="row">
				<div class="large-12 columns">
					<label><strong>New Password</strong></label>
					<input type="Password" size="20" value="{VALUE_NEWPASS}" name="newpass" id="newpass" autocomplete="new-password" />
					{ERROR_NEWPASS}
				</div>
			</div>
			<div class="row">
				<div class="large-12 columns">
					<label><strong>Confirm New Password</strong></label>
					<input type="Password" size="20" value="{VALUE_CONFIRMPASS}" name="confirmpassword" id="confirmpassword" autocomplete="new-password" />
					{ERROR_CONFIRMPASS}
				</div>
			</div>
			<div class="row">
				<div class="large-12 columns">
					<input class="button" type="submit" value="Update" name="action" id="action" />&nbsp;<input
						class="button" type="SUBMIT" value="Cancel" name="action" />
				</div>
			</div>
		</form>
	</div>
	<!-- END: CHANGEPASS -->
</div>
<!-- END: page -->