<?php

class PWIRE_Ajax_AccountTools_Widget extends WP_Widget
{
	public function __construct()
	{
		$widget_ops = array(
			'classname' => 'pwire-ajax-account-tools-widget',
			'description' => 'PharmacyWire Ajax Account Tools',
		);
		parent::__construct('pwire_ajax_account_tools_widget', 'PharmacyWire Ajax Account Tools', $widget_ops);
	}

	// contents of widget, frontend
	public function widget($args, $instance)
	{
		if ( !is_admin() ) {
			if (WebUser::isLoggedIn()) {
				$loggedInState = 'logged-in';
			} else {
				$loggedInState = 'logged-out';
			} 

			$hide_heading = (!empty($instance[ 'hide_heading' ]) && ($instance[ 'hide_heading' ] == 'on')) ? true : false;
			$vertical_menu = (!empty($instance['vertical_menu']) && $instance['vertical_menu'] == 'on') ? 'vertical' : '';
			$hide_account = (!empty($instance[ 'hide_account' ]) && ($instance[ 'hide_account' ] == 'on')) ? true : false;
			$hide_login = (!empty($instance[ 'hide_login' ]) && ($instance[ 'hide_login' ] == 'on')) ? true : false;
			$hide_cart = (!empty($instance[ 'hide_cart' ]) && ($instance[ 'hide_cart' ] == 'on')) ? true : false;
			?>

				<script>
					jQuery(($) => {

						const accountWidget = $('.pwire-account-tools-widget');
						const accountWidgetContent = accountWidget.find('.account-tools-widget-content');
						accountWidgetContent.hide();
						
						function updateAccountToolsWidget() {
							let r = 'get-account-tools-info';
							const cartRequest = $.ajax({
								type: 'POST',
								url: `${pw_json.request_url}?r=${r}&pw_nonce=${pw_json.nonce}`,
								success: (response) => {
									const pwireResponse = JSON.parse(response);

									if (pwireResponse.success === 1) {
										if (pwireResponse.cart.cart_item_count > 0) {
											accountWidget.find('.cart-quantity').addClass('cart-has-items').text(pwireResponse.cart.cart_item_count);
										} else {
											accountWidget.find('.cart-quantity').removeClass('cart-has-items').text('');
										}
									}

									if (pwireResponse.logged_in === 1) {
										accountWidget.find('.login-link').html($("<a>").attr('href', pw_json.logout_url).text('Log Out'));
										accountWidget.find('.account-link').html($("<a>").attr('href', pw_json.account_url).text('Account'));
									} else {
										accountWidget.find('.login-link').html($("<a>").attr('href', pw_json.login_url).text('Login'));
										accountWidget.find('.account-link').html($("<a>").attr('href', pw_json.register_url).text('Create Account'));
									}
								}
							});

							cartRequest.done(() => {
								accountWidgetContent.show();
							});
						}

						updateAccountToolsWidget();

						// update cart widget on cart change
						$('.pw-pharmacy-wrap').on('pwire:cart:updateCartForm pwire:cart:removeLineItem pwire:cart:orderSubmitted', () => {
							updateAccountToolsWidget();
						});
					});
				</script>

				<div class="pwire-ajax-account-tools-widget block widget pwire-account-tools-widget pwire-account-<?php echo $loggedInState; ?>">
					<?php if (!$hide_heading) : ?>
					<div class="grid-x block-title account-tools-widget-header">
						<h3>Account Tools</h3>
					</div>
					<?php endif; ?>
					<ul class="account-tools-widget-content menu <?php echo $vertical_menu; ?>">
						<?php if (!$hide_account) : ?>
						<li class="account-link menu-item"></li>
						<?php endif; ?>
						<?php if (!$hide_login) : ?>
						<li class="login-link menu-item"></li>
						<?php endif; ?>
						<?php if (!$hide_cart) : ?>
						<li class="cart-link menu-item shopping-cart"><a href="<?php echo PC_getShoppingURL(); ?>"><span class="cart-label">Cart</span> <span class="cart-quantity"></span></a></li>
						<?php endif; ?>
					</ul>
				</div>
			<?php
		} else {
			/* Simplified admin display - Now that block editor is enabled in WP by default, 
			this admin view avoids errors being generated by the block editor trying to render the frontend code */
			echo '<div style="border: 1px solid #555; padding: 0.5rem 0.5rem 0 0.5rem; border-radius: 2px;"><b><span class="dashicons dashicons-admin-generic" style="padding-top: 0.1em; color: #999;"></span> PharmacyWire Ajax Account Tools</b><br /><br /><a class="button">Display Options</a></div>';
		}
	}

	// admin options for widget
	public function form($instance)
	{
		?>
		<p>
			<input class="checkbox" type="checkbox" <?php if (!empty($instance[ 'vertical_menu' ])) : checked($instance[ 'vertical_menu' ], 'on'); endif; ?> id="<?php echo $this->get_field_id( 'vertical_menu' ); ?>" name="<?php echo $this->get_field_name( 'vertical_menu' ); ?>" /> 
			<label for="<?php echo $this->get_field_id( 'vertical_menu' ); ?>">Vertical menu</label>
		</p>
		<hr />
		<p>
			<input class="checkbox" type="checkbox" <?php if (!empty($instance[ 'hide_heading' ])) : checked($instance[ 'hide_heading' ], 'on' ); endif; ?> id="<?php echo $this->get_field_id( 'hide_heading' ); ?>" name="<?php echo $this->get_field_name( 'hide_heading' ); ?>" /> 
			<label for="<?php echo $this->get_field_id( 'hide_heading' ); ?>">Hide Account Heading</label>
		</p>
		<p>
			<input class="checkbox" type="checkbox" <?php if (!empty($instance[ 'hide_account' ])) : checked($instance[ 'hide_account' ], 'on' ); endif; ?> id="<?php echo $this->get_field_id( 'hide_account' ); ?>" name="<?php echo $this->get_field_name( 'hide_account' ); ?>" /> 
			<label for="<?php echo $this->get_field_id( 'hide_account' ); ?>">Hide Create Account/Account link.</label>
		</p>
		<p>
			<input class="checkbox" type="checkbox" <?php if (!empty($instance[ 'hide_login' ])) : checked($instance[ 'hide_login' ], 'on' ); endif; ?> id="<?php echo $this->get_field_id( 'hide_login' ); ?>" name="<?php echo $this->get_field_name( 'hide_login' ); ?>" /> 
			<label for="<?php echo $this->get_field_id( 'hide_login' ); ?>">Hide Login/Log Out link.</label>
		</p>
		<p>
			<input class="checkbox" type="checkbox" <?php if (!empty($instance[ 'hide_cart' ])) : checked($instance[ 'hide_cart' ], 'on' ); endif; ?> id="<?php echo $this->get_field_id( 'hide_cart' ); ?>" name="<?php echo $this->get_field_name( 'hide_cart' ); ?>" /> 
			<label for="<?php echo $this->get_field_id( 'hide_cart' ); ?>">Hide Cart link.</label>
		</p>
		<?php
	}

	// processing widget options to be saved
	public function update($new_instance, $old_instance)
	{
		return $new_instance;
	}

}

add_action('widgets_init', function () {
	register_widget('PWIRE_Ajax_AccountTools_Widget');
});
