<!-- BEGIN: PAGE -->
<div class="pw-pharmacy-wrap checkout_login grid-x grid-margin-x">
	<div class="returning_patient returning_customer cell small-6">
		<form class="login_form" data-abide data-validate-on-blur="true" novalidate method="post">
			<h2>Returning Customer</h2>
			<p>To continue, please enter your email address and password that you use for your account.</p>
			<label for="username">Email Address
				<input id="username" type="text" maxlength="50" class="email-address username" name="username" tabindex="10" placeholder="Email Address" autocomplete="username" required>
			</label>
			<label class="form-error" data-form-error-for="username">Valid email address is required.</label>
			
			<label for="password">Password
				<input id="password" type="password" name="password" class="password" tabindex="20" placeholder="password" autocomplete="password" required>
			</label>
			<label class="form-error" data-form-error-for="password">Valid password is required.</label>
			
			<button class="button" type="submit" name="returning_customer">Login</button>
			<div data-abide-error class="alert callout" aria-live="assertive" style="display: none;">
				<p><i class="fi-alert"></i>Invalid email address and/or password entered.</p>
			</div>
			<div class="forgot-password">
				<a href="/forgot-password">Forgot password</a>
			</div>
		</form>
		<div class="response"></div>
	</div>
	<div class="new_patient new_customer cell small-6">
		<h2>New Customer</h2>
		<p>Set up a new customer account and be able to, track the status of your order and place easy refill orders.
		</p>
		<a href="{ACTION}" class="button" name="new_customer">Continue</a>
	</div>
</div>
<!-- END: PAGE -->